(function(g){var window=this;var KAa=function(a,b){return g.Ub(a,b)},d6=function(a){g.Jm(a,"zx",g.wb());
return a},e6=function(a,b,c){g.za(c)||(c=[String(c)]);
g.Mm(a.g,b,c)},LAa=function(a,b){var c=[];
g.rk(b,function(a){try{var b=g.bD.prototype.l.call(this,a,!0)}catch(f){if("Storage: Invalid value was encountered"==f)return;throw f;}g.t(b)?g.aD(b)&&c.push(a):c.push(a)},a);
return c},MAa=function(a,b){var c=LAa(a,b);
(0,g.B)(c,function(a){g.bD.prototype.remove.call(this,a)},a)},NAa=function(a,b,c,d){var e=new g.Am(null,void 0);
a&&g.Bm(e,a);b&&g.Cm(e,b);c&&g.Dm(e,c);d&&g.Em(e,d);return e},OAa=function(a){g.VF[a]&&(a=g.VF[a],(0,g.B)(a,function(a){g.TF[a]&&delete g.TF[a]}),a.length=0)},PAa=function(a){var b=g.SF();
if(b)if(b.clear(a),a)OAa(a);else for(var c in g.VF)OAa(c)},f6=function(a){this.app=this.name=this.id="";
this.type="REMOTE_CONTROL";this.obfuscatedGaiaId=this.avatar=this.username="";this.o=!1;this.capabilities=new window.Set;this.experiments=new window.Set;this.theme="u";new g.um;this.g=this.l="";a&&(this.id=a.id||a.name,this.name=a.name,this.app=a.app,this.type=a.type||"REMOTE_CONTROL",this.username=a.user||"",this.avatar=a.userAvatarUri||"",this.obfuscatedGaiaId=a.obfuscatedGaiaId||"",this.theme=a.theme||"u",QAa(this,a.capabilities||""),RAa(this,a.experiments||""),this.l=a.remoteControllerUrl||"",
this.g=a.localChannelEncryptionKey||"")},QAa=function(a,b){a.capabilities.clear();
(0,g.Id)(b.split(","),g.Fa(KAa,SAa)).forEach(function(b){a.capabilities.add(b)})},RAa=function(a,b){a.experiments.clear();
b.split(",").forEach(function(b){a.experiments.add(b)})},g6=function(a){a=a||{};
this.name=a.name||"";this.id=a.id||a.screenId||"";this.token=a.token||a.loungeToken||"";this.uuid=a.uuid||a.dialId||""},h6=function(a,b){return!!b&&(a.id==b||a.uuid==b)},TAa=function(a){return{name:a.name,
screenId:a.id,loungeToken:a.token,dialId:a.uuid}},UAa=function(a){return new g6(a)},VAa=function(a){return g.za(a)?(0,g.I)(a,UAa):[]},i6=function(a){return a?'{name:"'+a.name+'",id:'+a.id.substr(0,6)+"..,token:"+(a.token?".."+a.token.slice(-6):"-")+",uuid:"+(a.uuid?".."+a.uuid.slice(-6):"-")+"}":"null"},j6=function(a){return g.za(a)?"["+(0,g.I)(a,i6).join(",")+"]":"null"},k6=function(){return"xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx".replace(/[xy]/g,function(a){var b=16*Math.random()|0;
return("x"==a?b:b&3|8).toString(16)})},WAa=function(a){return(0,g.I)(a,function(a){return{key:a.id,
name:a.name}})},l6=function(a,b){return g.La(a,function(a){return a||b?!a!=!b?!1:a.id==b.id:!0})},m6=function(a,b){return g.La(a,function(a){return h6(a,b)})},XAa=function(){var a=(0,g.OG)();
a&&MAa(a,a.g.Rd(!0))},n6=function(){var a=g.RG("yt-remote-connected-devices")||[];
g.gb(a);return a},YAa=function(a){if(g.Pa(a))return[];
var b=a[0].indexOf("#"),c=-1==b?a[0]:a[0].substring(0,b);return(0,g.I)(a,function(a,b){return 0==b?a:a.substring(c.length)})},ZAa=function(a){g.QG("yt-remote-connected-devices",a,86400)},p6=function(){if(o6)return o6;
var a=g.RG("yt-remote-device-id");a||(a=k6(),g.QG("yt-remote-device-id",a,31536E3));for(var b=n6(),c=1,d=a;g.D(b,d);)c++,d=a+"#"+c;return o6=d},q6=function(){var a=n6(),b=p6();
g.D(a,b);g.TG()&&g.jb(a,b);a=YAa(a);if(g.Pa(a))try{g.BG("remote_sid")}catch(c){}else try{g.AG("remote_sid",a.join(","),-1)}catch(c){}},$Aa=function(){return g.RG("yt-remote-session-browser-channel")},aBa=function(){return g.RG("yt-remote-local-screens")||[]},bBa=function(){g.QG("yt-remote-lounge-token-expiration",!0,86400)},cBa=function(a){5<a.length&&(a=a.slice(a.length-5));
var b=(0,g.I)(aBa(),function(a){return a.loungeToken}),c=(0,g.I)(a,function(a){return a.loungeToken});
(0,g.jm)(c,function(a){return!g.D(b,a)})&&bBa();
g.QG("yt-remote-local-screens",a,31536E3)},dBa=function(a,b){g.QG("yt-remote-session-browser-channel",a);
g.QG("yt-remote-session-screen-id",b);var c=n6(),d=p6();g.D(c,d)||c.push(d);ZAa(c);q6()},r6=function(a){a||(g.SG("yt-remote-session-screen-id"),g.SG("yt-remote-session-video-id"));
q6();a=n6();g.Ta(a,p6());ZAa(a)},eBa=function(){if(!s6){var a=g.mD();
a&&(s6=new g.WC(a))}return s6?!!s6.get("yt-remote-use-staging-server"):!1},fBa=function(){var a=window.document.createElement("a");
g.Xc(a,"https://www.gstatic.com/cv/js/sender/v1/cast_sender.js");a=a.href.replace(/^[a-zA-Z]+:\/\//,"//");return"js-"+g.Ab(a)},gBa=function(a,b){var c=g.Bd("SCRIPT");
c.id=a;c.onload=function(){b&&(0,window.setTimeout)(b,0)};
c.onreadystatechange=function(){switch(c.readyState){case "loaded":case "complete":c.onload()}};
g.Yc(c,g.ae("https://www.gstatic.com/cv/js/sender/v1/cast_sender.js"));var d=window.document.getElementsByTagName("head")[0]||window.document.body;d.insertBefore(c,d.firstChild);return c},hBa=function(){var a=fBa(),b=window.document.getElementById(a),c=b&&g.fF(b,"loaded");
c||b&&!c||(b=gBa(a,function(){g.fF(b,"loaded")||(g.eF(b,"loaded","true"),g.ZF(a),g.VD(g.Fa(PAa,a),0))}))},t6=function(a){return!!window.document.currentScript&&(-1!=window.document.currentScript.src.indexOf("?"+a)||-1!=window.document.currentScript.src.indexOf("&"+a))},iBa=function(){return"function"==typeof window.__onGCastApiAvailable?window.__onGCastApiAvailable:null},u6=function(a){a.length?jBa(a.shift(),function(){u6(a)}):v6()},kBa=function(a){return"chrome-extension://"+a+w6},jBa=function(a,
b,c){var d=window.document.createElement("script");
d.onerror=b;c&&(d.onload=c);d.src=a;(window.document.head||window.document.documentElement).appendChild(d)},x6=function(a){return 0<=window.navigator.userAgent.indexOf(a)},v6=function(){var a=iBa();
a&&a(!1,"No cast extension found")},y6=function(){if(lBa){var a=2,b=iBa(),c=function(){a--;
0==a&&b&&b(!0)};
window.__onGCastApiAvailable=c;jBa("//www.gstatic.com/cast/sdk/libs/sender/1.0/cast_framework.js",v6,c)}},mBa=function(){var a=window.__gCrWeb&&window.__gCrWeb.message&&window.__gCrWeb.message.invokeOnHost;
a&&(y6(),a({command:"cast.sender.init"}))},nBa=function(){y6();
var a=window.navigator.userAgent.match(/Chrome\/([0-9]+)/);u6(["//www.gstatic.com/eureka/clank/"+(a?(0,window.parseInt)(a[1],10):0)+w6,"//www.gstatic.com/eureka/clank"+w6])},z6=function(a,b,c){g.L.call(this);
this.C=null!=c?(0,g.z)(a,c):a;this.cd=b;this.B=(0,g.z)(this.AI,this);this.g=!1;this.l=0;this.o=this.xa=null;this.A=[]},A6=function(){},B6=function(a,b,c,d){this.g=a;
this.o=b;this.F=c;this.D=d||1;this.B=45E3;this.A=new g.Qm(this);this.l=new g.rg;this.l.setInterval(250)},pBa=function(a,b,c){a.vj=1;
a.ih=d6(b.clone());a.Ii=c;a.C=!0;oBa(a,null)},C6=function(a,b,c,d,e){a.vj=1;
a.ih=d6(b.clone());a.Ii=null;a.C=c;e&&(a.ZC=!1);oBa(a,d)},oBa=function(a,b){a.bk=(0,g.G)();
D6(a);a.Ah=a.ih.clone();e6(a.Ah,"t",a.D);a.Zl=0;a.Rc=a.g.Pq(a.g.Tl()?b:null);0<a.wr&&(a.Wo=new g.Tk((0,g.z)(a.pE,a,a.Rc),a.wr));a.A.T(a.Rc,"readystatechange",a.CT);var c=a.ii?g.ac(a.ii):{};a.Ii?(a.Gp="POST",c["Content-Type"]="application/x-www-form-urlencoded",a.Rc.send(a.Ah,a.Gp,a.Ii,c)):(a.Gp="GET",a.ZC&&!g.xd&&(c.Connection="close"),a.Rc.send(a.Ah,a.Gp,null,c));a.g.rf(1)},sBa=function(a,b,c){for(var d=!0;!a.Sh&&a.Zl<c.length;){var e=qBa(a,c);
if(e==E6){4==b&&(a.jh=4,F6(15),d=!1);break}else if(e==rBa){a.jh=4;F6(16);d=!1;break}else G6(a,e)}4==b&&0==c.length&&(a.jh=1,F6(17),d=!1);a.xf=a.xf&&d;d||(H6(a),I6(a))},qBa=function(a,b){var c=a.Zl,d=b.indexOf("\n",c);
if(-1==d)return E6;c=Number(b.substring(c,d));if((0,window.isNaN)(c))return rBa;d+=1;if(d+c>b.length)return E6;var e=b.substr(d,c);a.Zl=d+c;return e},uBa=function(a,b){a.bk=(0,g.G)();
D6(a);var c=b?window.location.hostname:"";a.Ah=a.ih.clone();g.Jm(a.Ah,"DOMAIN",c);g.Jm(a.Ah,"t",a.D);try{a.zf=new window.ActiveXObject("htmlfile")}catch(n){H6(a);a.jh=7;F6(22);I6(a);return}var d="<html><body>";if(b){for(var e="",f=0;f<c.length;f++){var k=c.charAt(f);if("<"==k)e+="\\x3c";else if(">"==k)e+="\\x3e";else{var l=k;if(l in J6)k=J6[l];else if(l in tBa)k=J6[l]=tBa[l];else{var m=l.charCodeAt(0);if(31<m&&127>m)k=l;else{if(256>m){if(k="\\x",16>m||256<m)k+="0"}else k="\\u",4096>m&&(k+="0");k+=
m.toString(16).toUpperCase()}k=J6[l]=k}e+=k}}d+='<script>document.domain="'+e+'"\x3c/script>'}d+="</body></html>";c=g.Zc(g.uc("b/12014412"),d);a.zf.open();a.zf.write(g.Qc(c));a.zf.close();a.zf.parentWindow.m=(0,g.z)(a.KS,a);a.zf.parentWindow.d=(0,g.z)(a.mC,a,!0);a.zf.parentWindow.rpcClose=(0,g.z)(a.mC,a,!1);c=a.zf.createElement("DIV");a.zf.parentWindow.document.body.appendChild(c);d=g.Hc(a.Ah.toString());d=g.qb(g.Ec(d));d=g.Zc(g.uc("b/12014412"),'<iframe src="'+d+'"></iframe>');c.innerHTML=g.Qc(d);
a.g.rf(1)},D6=function(a){a.jv=(0,g.G)()+a.B;
vBa(a,a.B)},vBa=function(a,b){if(null!=a.uk)throw Error("WatchDog timer not null");
a.uk=K6((0,g.z)(a.bT,a),b)},L6=function(a){a.uk&&(g.w.clearTimeout(a.uk),a.uk=null)},I6=function(a){a.g.ty()||a.Sh||a.g.Jo(a)},H6=function(a){L6(a);
g.$e(a.Wo);a.Wo=null;a.l.stop();g.Wm(a.A);if(a.Rc){var b=a.Rc;a.Rc=null;b.abort();b.dispose()}a.zf&&(a.zf=null)},G6=function(a,b){try{a.g.fC(a,b),a.g.rf(4)}catch(c){}},xBa=function(a,b,c,d,e){if(0==d)c(!1);
else{var f=e||0;d--;wBa(a,b,function(e){e?c(!0):g.w.setTimeout(function(){xBa(a,b,c,d,f)},f)})}},wBa=function(a,b,c){var d=new window.Image;
d.onload=function(){try{M6(d),c(!0)}catch(e){}};
d.onerror=function(){try{M6(d),c(!1)}catch(e){}};
d.onabort=function(){try{M6(d),c(!1)}catch(e){}};
d.ontimeout=function(){try{M6(d),c(!1)}catch(e){}};
g.w.setTimeout(function(){if(d.ontimeout)d.ontimeout()},b);
d.src=a},M6=function(a){a.onload=null;
a.onerror=null;a.onabort=null;a.ontimeout=null},yBa=function(a){this.g=a;
this.l=new A6},zBa=function(a){var b=N6(a.g,a.zk,"/mail/images/cleardot.gif");
d6(b);xBa(b.toString(),5E3,(0,g.z)(a.MH,a),3,2E3);a.rf(1)},P6=function(a){var b=a.g.H;
if(null!=b)F6(5),b?(F6(11),O6(a.g,a,!1)):(F6(12),O6(a.g,a,!0));else if(a.we=new B6(a,void 0,void 0,void 0),a.we.ii=a.tr,b=a.g,b=N6(b,b.Tl()?a.Yk:null,a.vr),F6(5),!g.vd||g.qc(10))e6(b,"TYPE","xmlhttp"),C6(a.we,b,!1,a.Yk,!1);else{e6(b,"TYPE","html");var c=a.we;a=!!a.Yk;c.vj=3;c.ih=d6(b.clone());uBa(c,a)}},Q6=function(a,b,c){this.g=1;
this.l=[];this.A=[];this.B=new A6;this.F=a||null;this.H=null!=b?b:null;this.C=c||!1},ABa=function(a,b){this.g=a;
this.map=b;this.context=null},BBa=function(a){g.bf.call(this,"statevent",a)},CBa=function(a,b){g.bf.call(this,"timingevent",a);
this.size=b},DBa=function(a){g.bf.call(this,"serverreachability",a)},GBa=function(a){EBa(a);
if(3==a.g){var b=a.Fl++,c=a.Bn.clone();g.Jm(c,"SID",a.o);g.Jm(c,"RID",b);g.Jm(c,"TYPE","terminate");R6(a,c);b=new B6(a,a.o,b,void 0);b.vj=2;b.ih=d6(c.clone());(new window.Image).src=b.ih;b.bk=(0,g.G)();D6(b)}FBa(a)},HBa=function(a){a.hI(1,0);
a.Bn=N6(a,null,a.sr);S6(a)},EBa=function(a){a.Xg&&(a.Xg.abort(),a.Xg=null);
a.wc&&(a.wc.cancel(),a.wc=null);a.pg&&(g.w.clearTimeout(a.pg),a.pg=null);T6(a);a.Wd&&(a.Wd.cancel(),a.Wd=null);a.Zg&&(g.w.clearTimeout(a.Zg),a.Zg=null)},IBa=function(a,b){if(0==a.g)throw Error("Invalid operation: sending map when state is closed");
a.l.push(new ABa(a.BO++,b));2!=a.g&&3!=a.g||S6(a)},S6=function(a){a.Wd||a.Zg||(a.Zg=K6((0,g.z)(a.kC,a),0),a.oj=0)},KBa=function(a,b){if(1==a.g){if(!b){a.Fl=Math.floor(1E5*Math.random());
var c=a.Fl++,d=new B6(a,"",c,void 0);d.ii=null;var e=U6(a),f=a.Bn.clone();g.Jm(f,"RID",c);g.Jm(f,"CVER","1");R6(a,f);pBa(d,f,e);a.Wd=d;a.g=2}}else 3==a.g&&(b?JBa(a,b):0==a.l.length||a.Wd||JBa(a))},JBa=function(a,b){if(b)if(6<a.Uh){a.l=a.A.concat(a.l);
a.A.length=0;var c=a.Fl-1;var d=U6(a)}else c=b.F,d=b.Ii;else c=a.Fl++,d=U6(a);var e=a.Bn.clone();g.Jm(e,"SID",a.o);g.Jm(e,"RID",c);g.Jm(e,"AID",a.Kj);R6(a,e);c=new B6(a,a.o,c,a.oj+1);c.ii=null;c.setTimeout(1E4+Math.round(1E4*Math.random()));a.Wd=c;pBa(c,e,d)},R6=function(a,b){if(a.qd){var c=a.qd.Wx();
c&&g.Jb(c,function(a,c){g.Jm(b,c,a)})}},U6=function(a){var b=Math.min(a.l.length,1E3),c=["count="+b];
if(6<a.Uh&&0<b){var d=a.l[0].g;c.push("ofs="+d)}else d=0;for(var e=0;e<b;e++){var f=a.l[e].g,k=a.l[e].map;f=6>=a.Uh?e:f-d;try{g.Jb(k,function(a,b){c.push("req"+f+"_"+b+"="+(0,window.encodeURIComponent)(a))})}catch(l){c.push("req"+f+"_type="+(0,window.encodeURIComponent)("_badmap"))}}a.A=a.A.concat(a.l.splice(0,b));
return c.join("&")},LBa=function(a){a.wc||a.pg||(a.D=1,a.pg=K6((0,g.z)(a.jC,a),0),a.cj=0)},V6=function(a){if(a.wc||a.pg||3<=a.cj)return!1;
a.D++;a.pg=K6((0,g.z)(a.jC,a),MBa(a,a.cj));a.cj++;return!0},O6=function(a,b,c){a.Fp=c;
a.Kf=b.xg;a.C||HBa(a)},T6=function(a){null!=a.Wh&&(g.w.clearTimeout(a.Wh),a.Wh=null)},MBa=function(a,b){var c=5E3+Math.floor(1E4*Math.random());
a.isActive()||(c*=2);return c*b},W6=function(a,b){if(2==b||9==b){var c=null;
a.qd&&(c=null);var d=(0,g.z)(a.xU,a);c||(c=new g.Am("//www.google.com/images/cleardot.gif"),d6(c));wBa(c.toString(),1E4,d)}else F6(2);NBa(a,b)},NBa=function(a,b){a.g=0;
a.qd&&a.qd.Ow(b);FBa(a);EBa(a)},FBa=function(a){a.g=0;
a.Kf=-1;if(a.qd)if(0==a.A.length&&0==a.l.length)a.qd.Eq();else{g.Wa(a.A);var b=g.Wa(a.l);a.A.length=0;a.l.length=0;a.qd.Eq(b)}},N6=function(a,b,c){var d=g.Km(c);
if(""!=d.l)b&&g.Cm(d,b+"."+d.l),g.Dm(d,d.B);else{var e=window.location;d=NAa(e.protocol,b?b+"."+e.hostname:e.hostname,e.port,c)}a.Kk&&g.Jb(a.Kk,function(a,b){g.Jm(d,b,a)});
g.Jm(d,"VER",a.Uh);R6(a,d);return d},K6=function(a,b){if(!g.Ba(a))throw Error("Fn must not be null and must be a function");
return g.w.setTimeout(function(){a()},b)},F6=function(a){X6.dispatchEvent(new BBa(X6,a))},OBa=function(){},PBa=function(a,b){this.action=a;
this.params=b||{}},Y6=function(a,b){g.L.call(this);
this.g=new g.Zt(this.BS,0,this);g.M(this,this.g);this.cd=5E3;this.l=0;if(g.Ba(a))b&&(a=(0,g.z)(a,b));else if(a&&g.Ba(a.handleEvent))a=(0,g.z)(a.handleEvent,a);else throw Error("Invalid listener argument");this.o=a},Z6=function(a,b,c){this.K=a;
this.C=b;this.o=new g.VC;this.l=new Y6(this.cV,this);this.g=this.Ya=null;this.I=!1;this.B=null;this.H="";this.F=this.A=0;this.D=[];this.M=c||!1},QBa=function(a){return{firstTestResults:[""],
secondTestResults:!a.g.Fp,sessionId:a.g.o,arrayId:a.g.Kj}},RBa=function(a,b){a.F=b||0;
a.l.stop();a.g&&(3==a.g.g&&KBa(a.g),GBa(a.g));a.F=0},$6=function(a){return!!a.g&&3==a.g.g},SBa=function(a,b){(a.C.loungeIdToken=b)||a.l.stop()},a7=function(a){this.port=this.domain="";
this.g="/api/lounge";this.l=!0;a=a||window.document.location.href;var b=g.Ig(a)||"";b&&(this.port=":"+b);this.domain=g.Hg(a)||"";a=g.Hb;0<=a.search("MSIE")&&(a=a.match(/MSIE ([\d.]+)/)[1],0>g.zb(a,"10.0")&&(this.l=!1))},b7=function(a,b){var c=a.g;
if(g.t(void 0)?0:a.l)c="https://"+a.domain+a.port+a.g;return g.Rg(c+b,{})},c7=function(a,b,c,d,e){a={format:"JSON",
method:"POST",context:a,timeout:5E3,withCredentials:!1,Hb:g.Fa(a.A,d,!0),onError:g.Fa(a.o,e),wd:g.Fa(a.B,e)};c&&(a.Lb=c,a.headers={"Content-Type":"application/x-www-form-urlencoded"});return g.sE(b,a)},WBa=function(){var a=TBa;
UBa();d7.push(a);VBa(d7)},e7=function(a,b){UBa();
var c=d7,d=XBa(a,String(b));g.Pa(c)?YBa(d):(VBa(c),(0,g.B)(c,function(a){a(d)}))},UBa=function(){d7||(d7=g.x("yt.mdx.remote.debug.handlers_")||[],g.wa("yt.mdx.remote.debug.handlers_",d7,void 0))},YBa=function(a){var b=(f7+1)%50;
f7=b;g7[b]=a;h7||(h7=49==b)},VBa=function(a){var b=g7;
if(b[0]){var c=f7,d=h7?c:-1;do{d=(d+1)%50;var e=b[d];(0,g.B)(a,function(a){a(e)})}while(d!=c);
g7=Array(50);f7=-1;h7=!1}},XBa=function(a,b){var c=((0,g.G)()-ZBa)/1E3;
c.toFixed&&(c=c.toFixed(3));var d=[];d.push("[",c+"s","] ");d.push("[","yt.mdx.remote","] ");d.push(a+": "+b,"\n");return d.join("")},i7=function(a){g.KF.call(this);
this.D=a;this.g=[]},$Ba=function(a,b){var c=a.get(b.uuid)||a.get(b.id);
if(c){var d=c.name;c.id=b.id||c.id;c.name=b.name;c.token=b.token;c.uuid=b.uuid||c.uuid;return c.name!=d}a.g.push(b);return!0},aCa=function(a,b){var c=a.g.length!=b.length;
a.g=(0,g.Id)(a.g,function(a){return!!l6(b,a)});
for(var d=0,e=b.length;d<e;d++)c=$Ba(a,b[d])||c;return c},bCa=function(a,b){var c=a.g.length;
a.g=(0,g.Id)(a.g,function(a){return!(a||b?!a!=!b?0:a.id==b.id:1)});
return a.g.length<c},j7=function(a,b,c,d){g.KF.call(this);
this.C=a;this.B=b;this.o=c;this.A=d;this.l=0;this.g=null;this.xa=window.NaN},l7=function(a){i7.call(this,"LocalScreenService");
this.o=a;this.l=window.NaN;k7(this);this.info("Initializing with "+j6(this.g))},cCa=function(a){if(a.g.length){var b=(0,g.I)(a.g,function(a){return a.id}),c=b7(a.o,"/pairing/get_lounge_token_batch");
c7(a.o,c,{screen_ids:b.join(",")},(0,g.z)(a.NI,a),(0,g.z)(a.MI,a))}},k7=function(a){var b=VAa(aBa());
b=(0,g.Id)(b,function(a){return!a.uuid});
return aCa(a,b)},m7=function(a,b){cBa((0,g.I)(a.g,TAa));
b&&bBa()},o7=function(a,b){g.KF.call(this);
this.C=b;var c=g.RG("yt-remote-online-screen-ids")||"";c=c?c.split(","):[];for(var d={},e=this.C(),f=0,k=e.length;f<k;++f){var l=e[f].id;d[l]=g.D(c,l)}this.g=d;this.B=a;this.o=this.A=window.NaN;this.l=null;n7("Initialized with "+g.yg(this.g))},dCa=function(a,b,c){var d=b7(a.B,"/pairing/get_screen_availability");
c7(a.B,d,{lounge_token:b.token},(0,g.z)(function(a){a=a.screens||[];for(var d=0,e=a.length;d<e;++d)if(a[d].loungeToken==b.token){c("online"==a[d].status);return}c(!1)},a),(0,g.z)(function(){c(!1)},a))},p7=function(a,b){a:if(g.Pb(b)!=g.Pb(a.g))var c=!1;
else{c=g.Rb(b);for(var d=0,e=c.length;d<e;++d)if(!a.g[c[d]]){c=!1;break a}c=!0}c||(n7("Updated online screens: "+g.yg(a.g)),a.g=b,a.R("screenChange"));eCa(a)},q7=function(a){(0,window.isNaN)(a.o)||g.XD(a.o);
a.o=g.VD((0,g.z)(a.pu,a),0<a.A&&a.A<(0,g.G)()?2E4:1E4)},n7=function(a){e7("OnlineScreenService",a)},fCa=function(a){var b={};
(0,g.B)(a.C(),function(a){a.token?b[a.token]=a.id:this.hc("Requesting availability of screen w/o lounge token.")});
return b},eCa=function(a){a=g.Rb(g.Lb(a.g,function(a){return a}));
g.gb(a);a.length?g.QG("yt-remote-online-screen-ids",a.join(","),60):g.SG("yt-remote-online-screen-ids")},r7=function(a){i7.call(this,"ScreenService");
this.C=a;this.l=this.o=null;this.A=[];this.B={};gCa(this)},iCa=function(a,b,c,d,e,f){a.info("getAutomaticScreenByIds "+c+" / "+b);
c||(c=a.B[b]);var k=a.ne();if(k=(c?m6(k,c):null)||m6(k,b)){k.uuid=b;var l=s7(a,k);dCa(a.l,l,function(a){e(a?l:null)})}else c?hCa(a,c,(0,g.z)(function(a){var f=s7(this,new g6({name:d,
screenId:c,loungeToken:a,dialId:b||""}));dCa(this.l,f,function(a){e(a?f:null)})},a),f):e(null)},jCa=function(a,b){for(var c=0,d=a.g.length;c<d;++c)if(a.g[c].name==b)return a.g[c];
return null},hCa=function(a,b,c,d){a.info("requestLoungeToken_ for "+b);
var e={Lb:{screen_ids:b},method:"POST",context:a,Hb:function(a,e){var f=e&&e.screens||[];f[0]&&f[0].screenId==b?c(f[0].loungeToken):d(Error("Missing lounge token in token response"))},
onError:function(){d(Error("Request screen lounge token failed"))}};
g.sE(b7(a.C,"/pairing/get_lounge_token_batch"),e)},kCa=function(a){a.g=a.o.ne();
var b=a.B,c={},d;for(d in b)c[b[d]]=d;b=0;for(d=a.g.length;b<d;++b){var e=a.g[b];e.uuid=c[e.id]||""}a.info("Updated manual screens: "+j6(a.g))},gCa=function(a){t7(a);
a.o=new l7(a.C);a.o.subscribe("screenChange",(0,g.z)(a.eJ,a));kCa(a);a.A=VAa(g.RG("yt-remote-automatic-screen-cache")||[]);t7(a);a.info("Initializing automatic screens: "+j6(a.A));a.l=new o7(a.C,(0,g.z)(a.ne,a,!0));a.l.subscribe("screenChange",(0,g.z)(function(){this.R("onlineScreenChange")},a))},s7=function(a,b){var c=a.get(b.id);
c?(c.uuid=b.uuid,b=c):((c=m6(a.A,b.uuid))?(c.id=b.id,c.token=b.token,b=c):a.A.push(b),g.QG("yt-remote-automatic-screen-cache",(0,g.I)(a.A,TAa)));t7(a);a.B[b.uuid]=b.id;g.QG("yt-remote-device-id-map",a.B,31536E3);return b},t7=function(a){a.B=g.RG("yt-remote-device-id-map")||{}},u7=function(a,b,c){g.KF.call(this);
this.M=c;this.H=a;this.l=b;this.o=null},v7=function(a,b){e7(a.M,b)},w7=function(a,b){u7.call(this,a,b,"CastSession");
this.g=null;this.A=0;this.C=(0,g.z)(this.iV,this);this.B=(0,g.z)(this.mT,this);this.A=g.VD((0,g.z)(function(){lCa(this,null)},this),12E4)},mCa=function(a){a.info("sendYoutubeMessage_: getMdxSessionStatus "+g.yg(void 0));
var b={type:"getMdxSessionStatus"};a.g?a.g.sendMessage("urn:x-cast:com.google.youtube.mdx",b,g.y,(0,g.z)(function(){v7(this,"Failed to send message: getMdxSessionStatus.")},a)):v7(a,"Sending yt message without session: "+g.yg(b))},lCa=function(a,b){g.XD(a.A);
if(b){if(a.info("onConnectedScreenId_: Received screenId: "+b),!a.o||a.o.id!=b){var c=(0,g.z)(a.Ko,a),d=(0,g.z)(a.te,a);a.jy(b,c,d,5)}}else a.te(Error("Waiting for session status timed out."))},x7=function(a,b,c){u7.call(this,a,b,"DialSession");
this.A=this.F=null;this.I="";this.N=c;this.B=null;this.D=g.y;this.C=window.NaN;this.K=(0,g.z)(this.lV,this);this.g=g.y},nCa=function(a){a.g=a.H.wE(a.I,a.l.label,a.l.friendlyName,(0,g.z)(function(a){this.g=g.y;
this.Ko(a)},a),(0,g.z)(function(a){this.g=g.y;
this.te(a)},a))},oCa=function(a){var b={};
b.pairingCode=a.I;b.theme=a.N;if(a.B){var c=a.B.currentTime||0;b.v=a.B.videoId;b.t=c}eBa()&&(b.env_useStageMdx=1);return g.Pg(b)},y7=function(a,b){u7.call(this,a,b,"ManualSession");
this.g=g.VD((0,g.z)(this.Lj,this,null),150)},z7=function(a,b,c,d){g.KF.call(this);
this.l=a;this.D=b||"233637DE";this.C=c||"cl";this.F=d||!1;this.g=null;this.B=!1;this.o=[];this.A=(0,g.z)(this.PR,this)},pCa=function(a,b){return b?g.La(a.o,function(a){return h6(b,a.label)},a):null},A7=function(a){e7("Controller",a)},TBa=function(a){window.chrome&&window.chrome.cast&&window.chrome.cast.logMessage&&window.chrome.cast.logMessage(a)},B7=function(a){return a.B||!!a.o.length||!!a.g},C7=function(a,b,c){b!=a.g&&(g.$e(a.g),(a.g=b)?(c?a.R("yt-remote-cast2-receiver-resumed",b.l):a.R("yt-remote-cast2-receiver-selected",
b.l),b.subscribe("sessionScreen",(0,g.z)(a.hC,a,b)),b.o?a.R("yt-remote-cast2-session-change",b.o):c&&a.g.Lj(null)):a.R("yt-remote-cast2-session-change",null))},qCa=function(a){var b=a.l.vE(),c=a.g&&a.g.l;
a=(0,g.I)(b,function(a){c&&h6(a,c.label)&&(c=null);var b=a.uuid?a.uuid:a.id,d=pCa(this,a);d?(d.label=b,d.friendlyName=a.name):(d=new window.chrome.cast.Receiver(b,a.name),d.receiverType=window.chrome.cast.ReceiverType.CUSTOM);return d},a);
c&&(c.receiverType!=window.chrome.cast.ReceiverType.CUSTOM&&(c=new window.chrome.cast.Receiver(c.label,c.friendlyName),c.receiverType=window.chrome.cast.ReceiverType.CUSTOM),a.push(c));return a},wCa=function(a,b,c,d,e,f,k){rCa()?sCa(b,e,f,k)&&(E7(!0),window.chrome&&window.chrome.cast&&window.chrome.cast.isAvailable?tCa(a,c):(window.__onGCastApiAvailable=function(b,d){b?tCa(a,c):(F7("Failed to load cast API: "+d),G7(!1),E7(!1),g.SG("yt-remote-cast-available"),g.SG("yt-remote-cast-receiver"),uCa(),
c(!1))},d?window.spf?window.spf.script.load("https://www.gstatic.com/cv/js/sender/v1/cast_sender.js","",void 0):hBa():x6("CriOS")?mBa():x6("Android")&&x6("Chrome/")&&window.navigator.presentation?nBa():window.chrome&&window.navigator.presentation&&!x6("Edge")?(y6(),u6(vCa.map(kBa))):v6())):D7("Cannot initialize because not running Chrome")},uCa=function(){D7("dispose");
var a=H7();a&&a.dispose();g.wa("yt.mdx.remote.cloudview.instance_",null,void 0);xCa(!1);g.XF(I7);I7.length=0},J7=function(){return!!g.RG("yt-remote-cast-installed")},yCa=function(){var a=g.RG("yt-remote-cast-receiver");
return a?a.friendlyName:null},zCa=function(){D7("clearCurrentReceiver");
g.SG("yt-remote-cast-receiver")},ACa=function(){return J7()?H7()?H7().getCastSession():(F7("getCastSelector: Cast is not initialized."),null):(F7("getCastSelector: Cast API is not installed!"),null)},L7=function(){J7()?H7()?K7()?(D7("Requesting cast selector."),H7().requestSession()):(D7("Wait for cast API to be ready to request the session."),I7.push(g.WF("yt-remote-cast2-api-ready",L7))):F7("requestCastSelector: Cast is not initialized."):F7("requestCastSelector: Cast API is not installed!")},M7=
function(a,b){K7()?H7().setConnectedScreenStatus(a,b):F7("setConnectedScreenStatus called before ready.")},rCa=function(){var a=0<=g.Hb.search(/ (CrMo|Chrome|CriOS)\//);
return g.RJ||a},BCa=function(a,b){H7().init(a,b)},sCa=function(a,b,c,d){var e=!1;
H7()||(a=new z7(a,b,c,d),a.subscribe("yt-remote-cast2-availability-change",function(a){g.QG("yt-remote-cast-available",a);g.$F("yt-remote-cast2-availability-change",a)}),a.subscribe("yt-remote-cast2-receiver-selected",function(a){D7("onReceiverSelected: "+a.friendlyName);
g.QG("yt-remote-cast-receiver",a);g.$F("yt-remote-cast2-receiver-selected",a)}),a.subscribe("yt-remote-cast2-receiver-resumed",function(a){D7("onReceiverResumed: "+a.friendlyName);
g.QG("yt-remote-cast-receiver",a)}),a.subscribe("yt-remote-cast2-session-change",function(a){D7("onSessionChange: "+i6(a));
a||g.SG("yt-remote-cast-receiver");g.$F("yt-remote-cast2-session-change",a)}),g.wa("yt.mdx.remote.cloudview.instance_",a,void 0),e=!0);
D7("cloudview.createSingleton_: "+e);return e},H7=function(){return g.x("yt.mdx.remote.cloudview.instance_")},tCa=function(a,b){G7(!0);
E7(!1);BCa(a,function(a){a?(xCa(!0),g.ZF("yt-remote-cast2-api-ready")):(F7("Failed to initialize cast API."),G7(!1),g.SG("yt-remote-cast-available"),g.SG("yt-remote-cast-receiver"),uCa());b(a)})},D7=function(a){e7("cloudview",a)},F7=function(a){e7("cloudview",a)},G7=function(a){D7("setCastInstalled_ "+a);
g.QG("yt-remote-cast-installed",a)},K7=function(){return!!g.x("yt.mdx.remote.cloudview.apiReady_")},xCa=function(a){D7("setApiReady_ "+a);
g.wa("yt.mdx.remote.cloudview.apiReady_",a,void 0)},E7=function(a){g.wa("yt.mdx.remote.cloudview.initializing_",a,void 0)},N7=function(a){this.index=-1;
this.videoId=this.listId="";this.volume=this.g=-1;this.muted=!1;this.audioTrackId=null;this.D=this.F=0;this.l=null;this.hasNext=this.Nf=!1;this.I=this.H=this.o=this.B=0;this.A=window.NaN;this.C=!1;this.reset(a)},O7=function(a){a.audioTrackId=null;
a.l=null;a.g=-1;a.Nf=!1;a.hasNext=!1;a.F=0;a.D=(0,g.G)();a.B=0;a.o=0;a.H=0;a.I=0;a.A=window.NaN;a.C=!1},P7=function(a){return a.kb()?((0,g.G)()-a.D)/1E3:0},Q7=function(a,b){a.F=b;
a.D=(0,g.G)()},R7=function(a){switch(a.g){case 1:case 1081:return((0,g.G)()-a.D)/1E3+a.F;
case -1E3:return 0}return a.F},S7=function(a,b,c){var d=a.videoId;
a.videoId=b;a.index=c;b!=d&&O7(a)},T7=function(a){var b={};
b.index=a.index;b.listId=a.listId;b.videoId=a.videoId;b.playerState=a.g;b.volume=a.volume;b.muted=a.muted;b.audioTrackId=a.audioTrackId;b.trackData=g.bc(a.l);b.hasPrevious=a.Nf;b.hasNext=a.hasNext;b.playerTime=a.F;b.playerTimeAt=a.D;b.seekableStart=a.B;b.seekableEnd=a.o;b.duration=a.H;b.loadedTime=a.I;b.liveIngestionTime=a.A;return b},V7=function(a,b){g.KF.call(this);
this.g=0;this.A=a;this.C=[];this.B=new g.lC;this.o=this.l=null;this.H=(0,g.z)(this.lP,this);this.D=(0,g.z)(this.Il,this);this.F=(0,g.z)(this.kP,this);this.I=(0,g.z)(this.yP,this);var c=0;a?(c=a.getProxyState(),3!=c&&(a.subscribe("proxyStateChange",this.tv,this),CCa(this))):c=3;0!=c&&(b?this.tv(c):g.VD((0,g.z)(function(){this.tv(c)},this),0));
var d=ACa();d&&U7(this,d);this.subscribe("yt-remote-cast2-session-change",this.I)},W7=function(a){return new N7(a.A.getPlayerContextData())},CCa=function(a){(0,g.B)("nowAutoplaying autoplayDismissed remotePlayerChange remoteQueueChange autoplayModeChange autoplayUpNext previousNextChange".split(" "),function(a){this.C.push(this.A.subscribe(a,g.Fa(this.LR,a),this))},a)},DCa=function(a){(0,g.B)(a.C,function(a){this.A.unsubscribeByKey(a)},a);
a.C.length=0},X7=function(a,b){50>a.B.Fc()&&g.nC(a.B,b)},Z7=function(a,b,c){var d=W7(a);
Q7(d,c);-1E3!=d.g&&(d.g=b);Y7(a,d)},$7=function(a,b,c){a.A.sendMessage(b,c)},Y7=function(a,b){DCa(a);
a.A.setPlayerContextData(T7(b));CCa(a)},U7=function(a,b){a.o&&(a.o.removeUpdateListener(a.H),a.o.removeMediaListener(a.D),a.Il(null));
a.o=b;a.o&&(e7("CP","Setting cast session: "+a.o.sessionId),a.o.addUpdateListener(a.H),a.o.addMediaListener(a.D),a.o.media.length&&a.Il(a.o.media[0]))},ECa=function(a){var b=a.l.media,c=a.l.customData;
if(b&&c){var d=W7(a);b.contentId!=d.videoId&&e7("CP","Cast changing video to: "+b.contentId);d.videoId=b.contentId;d.g=c.playerState;Q7(d,a.l.getEstimatedTime());Y7(a,d)}else e7("CP","No cast media video. Ignoring state update.")},a8=function(a,b,c){return(0,g.z)(function(a){this.hc("Failed to "+b+" with cast v2 channel. Error code: "+a.code);
a.code!=window.chrome.cast.ErrorCode.TIMEOUT&&(this.hc("Retrying "+b+" using MDx browser channel."),$7(this,b,c))},a)},b8=function(a,b,c){g.KF.call(this);
this.B=window.NaN;this.N=!1;this.I=this.H=this.K=this.M=window.NaN;this.P=[];this.A=this.D=this.o=this.Za=this.g=null;this.oa=a;this.P.push(g.uF(window,"beforeunload",(0,g.z)(this.EI,this)));this.l=[];this.Za=new N7;this.X=b.id;this.g=FCa(this,c);this.g.subscribe("handlerOpened",this.pP,this);this.g.subscribe("handlerClosed",this.mP,this);this.g.subscribe("handlerError",this.nP,this);this.g.subscribe("handlerMessage",this.oP,this);SBa(this.g,b.token);this.subscribe("remoteQueueChange",function(){var a=
this.Za.videoId;g.TG()&&g.QG("yt-remote-session-video-id",a)},this)},c8=function(a){e7("conn",a)},FCa=function(a,b){return new Z6(b7(a.oa,"/bc"),b)},d8=function(a,b){a.R("proxyStateChange",b)},GCa=function(a){a.B=g.VD((0,g.z)(function(){c8("Connecting timeout");
this.C(1)},a),2E4)},e8=function(a){g.XD(a.B);
a.B=window.NaN},f8=function(a){g.XD(a.M);
a.M=window.NaN},HCa=function(a){g8(a);
a.K=g.VD((0,g.z)(function(){h8(this,"getNowPlaying")},a),2E4)},g8=function(a){g.XD(a.K);
a.K=window.NaN},JCa=function(a,b){b&&(e8(a),f8(a));
b==($6(a.g)&&(0,window.isNaN)(a.B))?b&&(d8(a,1),h8(a,"getSubtitlesTrack")):b?(a.W()&&a.Za.reset(),d8(a,1),h8(a,"getNowPlaying"),ICa(a)):a.C(1)},KCa=function(a,b){var c=b.params.videoId;
delete b.params.videoId;c==a.Za.videoId&&(g.Xb(b.params)?a.Za.l=null:a.Za.l=b.params,a.R("remotePlayerChange"))},LCa=function(a,b){var c=b.params.videoId||b.params.video_id,d=(0,window.parseInt)(b.params.currentIndex,10);
a.Za.listId=b.params.listId||a.Za.listId;S7(a.Za,c,d);a.R("remoteQueueChange")},NCa=function(a,b){b.params=b.params||{};
LCa(a,b);MCa(a,b);a.R("autoplayDismissed")},MCa=function(a,b){var c=(0,window.parseInt)(b.params.currentTime||b.params.current_time,10);
Q7(a.Za,(0,window.isNaN)(c)?0:c);c=(0,window.parseInt)(b.params.state,10);c=(0,window.isNaN)(c)?-1:c;-1==c&&-1E3==a.Za.g&&(c=-1E3);a.Za.g=c;c=Number(b.params.loadedTime);a.Za.I=(0,window.isNaN)(c)?0:c;c=Number(b.params.duration);a.Za.H=(0,window.isNaN)(c)?0:c;c=a.Za;var d=Number(b.params.liveIngestionTime);c.A=d;c.C=(0,window.isNaN)(d)?!1:!0;c=a.Za;d=Number(b.params.seekableStartTime);var e=Number(b.params.seekableEndTime);c.B=(0,window.isNaN)(d)?0:d;c.o=(0,window.isNaN)(e)?0:e;1==a.Za.g?HCa(a):g8(a);
a.R("remotePlayerChange")},OCa=function(a,b){if(-1E3!=a.Za.g){var c=1085;
switch((0,window.parseInt)(b.params.adState,10)){case 1:c=1081;break;case 2:c=1084;break;case 0:c=1083}a.Za.g=c;c=(0,window.parseInt)(b.params.currentTime,10);Q7(a.Za,(0,window.isNaN)(c)?0:c);a.R("remotePlayerChange")}},PCa=function(a,b){var c="true"==b.params.muted;
a.Za.volume=(0,window.parseInt)(b.params.volume,10);a.Za.muted=c;a.R("remotePlayerChange")},QCa=function(a,b){a.D=b.params.videoId;
a.R("nowAutoplaying",(0,window.parseInt)(b.params.timeout,10))},RCa=function(a,b){var c="true"==b.params.hasNext;
a.Za.Nf="true"==b.params.hasPrevious;a.Za.hasNext=c;a.R("previousNextChange")},ICa=function(a){g.XD(a.I);
a.I=g.VD((0,g.z)(a.C,a,1),864E5)},h8=function(a,b,c){c?c8("Sending: action="+b+", params="+g.yg(c)):c8("Sending: action="+b);
a.g.sendMessage(b,c)},i8=function(a){i7.call(this,"ScreenServiceProxy");
this.bd=a;this.l=[];this.l.push(this.bd.$_s("screenChange",(0,g.z)(this.gV,this)));this.l.push(this.bd.$_s("onlineScreenChange",(0,g.z)(this.lR,this)))},WCa=function(a){var b={device:"Desktop",
app:"youtube-desktop"};b=g.PD("MDX_CONFIG")||b;XAa();q6();j8||(j8=new a7(b?b.loungeApiHost:void 0),eBa()&&(j8.g="/api/loungedev"));k8||(k8=g.x("yt.mdx.remote.deferredProxies_")||[],g.wa("yt.mdx.remote.deferredProxies_",k8,void 0));SCa();var c=l8();if(!c){var d=new r7(j8);g.wa("yt.mdx.remote.screenService_",d,void 0);c=l8();var e=!1,f=void 0,k=void 0,l=!1;b&&(e=!!b.loadCastApiSetupScript,f=b.appId,k=b.theme,l=!!b.disableDial);wCa(a,d,function(a){a?m8()&&M7(m8(),"YouTube TV"):d.subscribe("onlineScreenChange",
function(){g.$F("yt-remote-receiver-availability-change")})},e,f,k,l)}b&&!g.x("yt.mdx.remote.initialized_")&&(g.wa("yt.mdx.remote.initialized_",!0,void 0),n8("Initializing: "+g.yg(b)),o8.push(g.WF("yt-remote-cast2-availability-change",function(){g.$F("yt-remote-receiver-availability-change")})),o8.push(g.WF("yt-remote-cast2-receiver-selected",function(){p8(null);
g.$F("yt-remote-auto-connect","cast-selector-receiver")})),o8.push(g.WF("yt-remote-cast2-receiver-resumed",function(){g.$F("yt-remote-receiver-resumed","cast-selector-receiver")})),o8.push(g.WF("yt-remote-cast2-session-change",TCa)),o8.push(g.WF("yt-remote-connection-change",function(a){a?M7(m8(),"YouTube TV"):q8()||(M7(null,null),zCa())})),a=r8(),b.isAuto&&(a.id+="#dial"),g.QF("desktop_enable_autoplay")&&(a.capabilities=["atp"]),a.name=b.device,a.app=b.app,(k=b.theme)&&(a.theme=k),n8(" -- with channel params: "+
g.yg(a)),UCa(a),c.start(),m8()||VCa())},YCa=function(){var a=XCa();
J7()&&g.RG("yt-remote-cast-available")&&a.push({key:"cast-selector-receiver",name:"Cast..."});return a},XCa=function(){var a=l8().bd.$_gos();
var b=s8();b&&t8()&&(l6(a,b)||a.push(b));return WAa(a)},u8=function(){var a=ZCa();
!a&&J7()&&yCa()&&(a={key:"cast-selector-receiver",name:yCa()});return a},ZCa=function(){var a=XCa(),b=s8();
b||(b=q8());return g.La(a,function(a){return b&&h6(b,a.key)?!0:!1})},s8=function(){var a=m8();
if(!a)return null;var b=l8().ne();return m6(b,a)},TCa=function(a){n8("remote.onCastSessionChange_: "+i6(a));
if(a){var b=s8();b&&b.id==a.id?M7(b.id,"YouTube TV"):(b&&v8(),w8(a,1))}else t8()&&v8()},v8=function(){K7()?H7().stopSession():F7("stopSession called before API ready.");
var a=t8();a&&(a.disconnect(1),x8(null))},y8=function(){var a=t8();
return!!a&&3!=a.getProxyState()},n8=function(a){e7("remote",a)},l8=function(){if(!z8){var a=g.x("yt.mdx.remote.screenService_");
z8=a?new i8(a):null}return z8},m8=function(){return g.x("yt.mdx.remote.currentScreenId_")},$Ca=function(a){g.wa("yt.mdx.remote.currentScreenId_",a,void 0)},aDa=function(){return g.x("yt.mdx.remote.connectData_")},p8=function(a){g.wa("yt.mdx.remote.connectData_",a,void 0)},t8=function(){return g.x("yt.mdx.remote.connection_")},x8=function(a){var b=t8();
p8(null);a||$Ca("");g.wa("yt.mdx.remote.connection_",a,void 0);k8&&((0,g.B)(k8,function(b){b(a)}),k8.length=0);
b&&!a?g.$F("yt-remote-connection-change",!1):!b&&a&&g.$F("yt-remote-connection-change",!0)},q8=function(){var a=g.TG();
if(!a)return null;var b=l8().ne();return m6(b,a)},w8=function(a,b){s8()&&s8();
$Ca(a.id);var c=new b8(j8,a,r8());c.connect(b,aDa());c.subscribe("beforeDisconnect",function(a){g.$F("yt-remote-before-disconnect",a)});
c.subscribe("beforeDispose",function(){t8()&&x8(null)});
x8(c)},VCa=function(){var a=q8();
a?(n8("Resume connection to: "+i6(a)),w8(a,0)):(r6(),zCa(),n8("Skipping connecting because no session screen found."))},SCa=function(){var a=r8();
if(g.Xb(a)){a=p6();var b=g.RG("yt-remote-session-name")||"",c=g.RG("yt-remote-session-app")||"";a={device:"REMOTE_CONTROL",id:a,name:b,app:c,mdxVersion:3};g.wa("yt.mdx.remote.channelParams_",a,void 0)}},r8=function(){return g.x("yt.mdx.remote.channelParams_")||{}},UCa=function(a){a?(g.QG("yt-remote-session-app",a.app),g.QG("yt-remote-session-name",a.name)):(g.SG("yt-remote-session-app"),g.SG("yt-remote-session-name"));
g.wa("yt.mdx.remote.channelParams_",a,void 0)},A8=function(a,b,c){g.L.call(this);
this.F=a;this.l=b;this.o=new g.HF(this);g.M(this,this.o);this.o.O(b,"onCaptionsTrackListChanged",this.DQ);this.o.O(b,"captionschanged",this.jP);this.o.O(b,"captionssettingschanged",this.ED);this.o.O(b,"videoplayerreset",this.Lo);this.o.O(b,"mdxautoplaycancel",this.LH);this.P=this.o.O(b,"onVolumeChange",this.RB);this.D=!1;this.g=c;c.subscribe("proxyStateChange",this.eC,this);c.subscribe("remotePlayerChange",this.Ll,this);c.subscribe("remoteQueueChange",this.Lo,this);c.subscribe("autoplayUpNext",this.AB,
this);c.subscribe("previousNextChange",this.bC,this);c.subscribe("nowAutoplaying",this.TB,this);c.subscribe("autoplayDismissed",this.zB,this);this.suggestion=null;this.H=new g.YO(64);this.A=new g.Zt(this.AD,500,this);g.M(this,this.A);this.B=new g.Zt(this.BD,1E3,this);g.M(this,this.B);this.K=new z6(this.JU,0,this);g.M(this,this.K);this.C={};this.M=new g.Zt(this.hE,1E3,this);g.M(this,this.M);this.I=new g.Tk(this.nN,1E3,this);g.M(this,this.I);this.N=g.y;this.ED();this.Lo();this.Ll()},B8=function(a,b){var c=
a.F,d=a.l.ea().lengthSeconds;
c.H=b||0;c.g.R("progresssync",b,d)},bDa=function(a){B8(a,0);
a.A.stop();C8(a,new g.YO(64))},E8=function(a,b){if(D8(a)&&!a.D){var c=null;
b&&(c={style:a.l.Bi()},g.dc(c,b));a.g.sD(a.l.ea(1).videoId,c);a.C=W7(a.g).l}},F8=function(a,b){var c=a.l.Xf();
if(c){var d=c.ie();var e=c.listId.toString()}var f=a.l.ea(1);c=a.g;var k=f.videoId,l=d;d=f.playerParams;f=f.Gj;var m=W7(c),n=e||m.listId;l=l||0;var q={videoId:k,currentIndex:l};S7(m,k,l);g.t(b)&&(Q7(m,b),q.currentTime=b);g.t(n)&&(q.listId=n);null!=d&&(q.playerParams=d);null!=f&&(q.clickTrackingParams=f);$7(c,"setPlaylist",q);e||Y7(c,m);C8(a,new g.YO(1))},cDa=function(a,b){if(b){var c=a.l.Ac("captions","tracklist",{fz:1});
c&&c.length?(a.l.Jd("captions","track",b),a.D=!1):(a.l.Oj("captions"),a.D=!0)}else a.l.Jd("captions","track",{})},D8=function(a){return W7(a.g).videoId==a.l.ea(1).videoId},C8=function(a,b){a.B.stop();
var c=a.H;if(!g.fP(c,b)){var d=g.X(b,2);d!=g.X(a.H,2)&&g.XU(a.l,d);a.H=b;dDa(a.F,c,b)}},G8=function(a){g.W.call(this,{G:"div",
L:"ytp-remote",J:[{G:"div",L:"ytp-remote-display-status",J:[{G:"div",L:"ytp-remote-display-status-icon",J:[g.toa()]},{G:"div",L:"ytp-remote-display-status-text",J:["{{statustext}}"]}]}]});this.l=new g.DV(this,250);g.M(this,this.l);this.o=a;this.O(a,"presentingplayerstatechange",this.A);eDa(this,g.UU(a))},eDa=function(a,b){if(3==a.o.Ta()){var c={RECEIVER_NAME:a.o.Ac("remote","currentReceiver").name};
c=g.X(b,128)?g.V("YTP_MDX_STATUS_ERROR_2",c):b.kb()||g.X(b,4)?g.V("YTP_MDX_STATUS_PLAYING_2",c):g.V("YTP_MDX_STATUS_CONNECTED_2",c);a.updateValue("statustext",c);a.l.show()}else a.l.hide()},H8=function(a,b){g.JZ.call(this,g.V("YTP_MDX_TITLE"),0,a,b);
this.l=a;this.F={};this.O(a,"onMdxReceiversChange",this.I);this.O(a,"presentingplayerstatechange",this.I);this.I()},I8=function(a){g.rV.call(this,a);
g.VG({YTP_MDX_CAST_SELECTOR:"\u0625\u0631\u0633\u0627\u0644...",YTP_MDX_MY_COMPUTER:"\u0647\u0630\u0627 \u0627\u0644\u0643\u0645\u0628\u064a\u0648\u062a\u0631",YTP_MDX_PLAYER_ERROR:"\u0647\u0630\u0627 \u0627\u0644\u0641\u064a\u062f\u064a\u0648 \u063a\u064a\u0631 \u0645\u062a\u0627\u062d \u0644\u0644\u062a\u0634\u063a\u064a\u0644 \u0639\u0646 \u0628\u064f\u0639\u062f.",YTP_MDX_STATUS_CONNECTED_2:"\u062a\u0645 \u0627\u0644\u0627\u062a\u0635\u0627\u0644 \u0628\u0640 $RECEIVER_NAME",YTP_MDX_STATUS_ERROR_2:"\u062d\u062f\u062b \u062e\u0637\u0623 \u0641\u064a $RECEIVER_NAME",
YTP_MDX_STATUS_PLAYING_2:"\u064a\u062a\u0645 \u0627\u0644\u062a\u0634\u063a\u064a\u0644 \u0639\u0644\u0649 $RECEIVER_NAME",YTP_MDX_TITLE:"\u062a\u0634\u063a\u064a\u0644 \u0639\u0644\u0649"});this.o={key:k6(),name:g.V("YTP_MDX_MY_COMPUTER")};this.B=null;this.C=[];this.I=this.l=null;this.F=[this.o];this.A=this.o;this.D=new g.YO(64);this.H=0;if(!g.CM(g.Y(this.g))){a=this.g;var b=g.kI(a);b&&(b=b.so())&&(b=new H8(a,b),g.M(this,b));b=new G8(a);g.M(this,b);g.lV(a,b.element,4)}},dDa=function(a,b,c){a.D=c;
a.g.R("presentingplayerstatechange",new g.lP(c,b))},J8=function(a,b){if(b.key!=a.A.key)if(b.key==a.o.key)v8();
else{a.A=b;var c=a.g.getPlaylistId();var d=a.g.ea(1),e=d.videoId;if(c||e){var f=a.g.Xf();if(f){var k=[];for(var l=0;l<f.getLength();l++)k[l]=f.oc(l).videoId}else k=[e];f=a.g.getCurrentTime(1);c={videoIds:k,listId:c,videoId:e,playerParams:d.playerParams,clickTrackingParams:d.Gj,index:Math.max(a.g.gA(),0),currentTime:0==f?void 0:f}}else c=null;n8("Connecting to: "+g.yg(b));"cast-selector-receiver"==b.key?(p8(c||null),K7()?H7().setLaunchParams(c||null):F7("setLaunchParams called before ready.")):!c&&
y8()&&m8()==b.key?g.$F("yt-remote-connection-change",!0):(v8(),p8(c||null),c=l8().ne(),(c=m6(c,b.key))&&w8(c,1))}},tBa={"\x00":"\\0",
"\b":"\\b","\f":"\\f","\n":"\\n","\r":"\\r","\t":"\\t","\x0B":"\\x0B",'"':'\\"',"\\":"\\\\","<":"<"},J6={"'":"\\'"},fDa={},SAa={xW:"atp",O0:"ska",e0:"que",r_:"mus",K0:"sus"};
f6.prototype.kn=function(){var a=new f6({id:this.id,name:this.name,app:this.app,type:this.type,user:this.username,userAvatarUri:this.avatar,obfuscatedGaiaId:this.obfuscatedGaiaId,theme:this.theme,capabilities:Array.from(this.capabilities.values()).join(","),experiments:Array.from(this.experiments.values()).join(",")});a.o=this.o;a.l=this.l;a.g=this.g};
var s6,o6="",w6=t6("loadGamesSDK")?"/cast_game_sender.js":"/cast_sender.js",lBa=t6("loadCastFramework")||t6("loadCastApplicationFramework"),vCa=["pkedcjkdefgpdelpbcmbmeomcjbeemfm","enhhojjnijigcajfphajepfemndkmdlo"];g.A(z6,g.L);g.h=z6.prototype;g.h.zI=function(a){this.A=arguments;this.g=!1;this.xa?this.o=(0,g.G)()+this.cd:this.xa=g.sg(this.B,this.cd)};
g.h.stop=function(){this.xa&&(g.tg(this.xa),this.xa=null);this.o=null;this.g=!1;this.A=[]};
g.h.pause=function(){++this.l};
g.h.resume=function(){this.l&&(--this.l,!this.l&&this.g&&(this.g=!1,this.C.apply(null,this.A)))};
g.h.V=function(){this.stop();z6.Z.V.call(this)};
g.h.AI=function(){this.o?(this.xa=g.sg(this.B,this.o-(0,g.G)()),this.o=null):(this.xa=null,this.l?this.g=!0:(this.g=!1,this.C.apply(null,this.A)))};A6.prototype.stringify=function(a){return g.w.JSON.stringify(a,void 0)};
A6.prototype.parse=function(a){return g.w.JSON.parse(a,void 0)};g.h=B6.prototype;g.h.ii=null;g.h.xf=!1;g.h.uk=null;g.h.jv=null;g.h.bk=null;g.h.vj=null;g.h.ih=null;g.h.Ah=null;g.h.Ii=null;g.h.Rc=null;g.h.Zl=0;g.h.zf=null;g.h.Gp=null;g.h.jh=null;g.h.Zk=-1;g.h.ZC=!0;g.h.Sh=!1;g.h.wr=0;g.h.Wo=null;var rBa={},E6={};g.h=B6.prototype;g.h.setTimeout=function(a){this.B=a};
g.h.CT=function(a){a=a.target;var b=this.Wo;b&&3==g.jx(a)?b.tj():this.pE(a)};
g.h.pE=function(a){try{if(a==this.Rc)a:{var b=g.jx(this.Rc),c=this.Rc.l,d=this.Rc.getStatus();if(g.vd&&!g.qc(10)||g.xd&&!g.pc("420+")){if(4>b)break a}else if(3>b||3==b&&!g.df&&!g.rx(this.Rc))break a;this.Sh||4!=b||7==c||(8==c||0>=d?this.g.rf(3):this.g.rf(2));L6(this);var e=this.Rc.getStatus();this.Zk=e;var f=g.rx(this.Rc);(this.xf=200==e)?(4==b&&H6(this),this.C?(sBa(this,b,f),g.df&&this.xf&&3==b&&(this.A.T(this.l,"tick",this.zT),this.l.start())):G6(this,f),this.xf&&!this.Sh&&(4==b?this.g.Jo(this):
(this.xf=!1,D6(this)))):(400==e&&0<f.indexOf("Unknown SID")?(this.jh=3,F6(13)):(this.jh=0,F6(14)),H6(this),I6(this))}}catch(k){this.Rc&&g.rx(this.Rc)}finally{}};
g.h.zT=function(){var a=g.jx(this.Rc),b=g.rx(this.Rc);this.Zl<b.length&&(L6(this),sBa(this,a,b),this.xf&&4!=a&&D6(this))};
g.h.KS=function(a){K6((0,g.z)(this.JS,this,a),0)};
g.h.JS=function(a){this.Sh||(L6(this),G6(this,a),D6(this))};
g.h.mC=function(a){K6((0,g.z)(this.IS,this,a),0)};
g.h.IS=function(a){this.Sh||(H6(this),this.xf=a,this.g.Jo(this),this.g.rf(4))};
g.h.cancel=function(){this.Sh=!0;H6(this)};
g.h.bT=function(){this.uk=null;var a=(0,g.G)();0<=a-this.jv?(2!=this.vj&&this.g.rf(3),H6(this),this.jh=2,F6(18),I6(this)):vBa(this,this.jv-a)};g.h=yBa.prototype;g.h.tr=null;g.h.we=null;g.h.Xo=!1;g.h.uy=null;g.h.yn=null;g.h.ur=null;g.h.vr=null;g.h.Ne=null;g.h.xg=-1;g.h.Yk=null;g.h.zk=null;g.h.connect=function(a){this.vr=a;a=N6(this.g,null,this.vr);F6(3);this.uy=(0,g.G)();var b=this.g.F;null!=b?(this.Yk=b[0],(this.zk=b[1])?(this.Ne=1,zBa(this)):(this.Ne=2,P6(this))):(e6(a,"MODE","init"),this.we=new B6(this,void 0,void 0,void 0),this.we.ii=this.tr,C6(this.we,a,!1,null,!0),this.Ne=0)};
g.h.MH=function(a){if(a)this.Ne=2,P6(this);else{F6(4);var b=this.g;b.Kf=b.Xg.xg;W6(b,9)}a&&this.rf(2)};
g.h.Pq=function(a){return this.g.Pq(a)};
g.h.abort=function(){this.we&&(this.we.cancel(),this.we=null);this.xg=-1};
g.h.ty=function(){return!1};
g.h.fC=function(a,b){this.xg=a.Zk;if(0==this.Ne)if(b){try{var c=this.l.parse(b)}catch(d){c=this.g;c.Kf=this.xg;W6(c,2);return}this.Yk=c[0];this.zk=c[1]}else c=this.g,c.Kf=this.xg,W6(c,2);else if(2==this.Ne)if(this.Xo)F6(7),this.ur=(0,g.G)();else if("11111"==b){if(F6(6),this.Xo=!0,this.yn=(0,g.G)(),c=this.yn-this.uy,!g.vd||g.qc(10)||500>c)this.xg=200,this.we.cancel(),F6(12),O6(this.g,this,!0)}else F6(8),this.yn=this.ur=(0,g.G)(),this.Xo=!1};
g.h.Jo=function(){this.xg=this.we.Zk;if(this.we.xf)0==this.Ne?this.zk?(this.Ne=1,zBa(this)):(this.Ne=2,P6(this)):2==this.Ne&&((!g.vd||g.qc(10)?!this.Xo:200>this.ur-this.yn)?(F6(11),O6(this.g,this,!1)):(F6(12),O6(this.g,this,!0)));else{0==this.Ne?F6(9):2==this.Ne&&F6(10);var a=this.g;a.Kf=this.xg;W6(a,2)}};
g.h.Tl=function(){return this.g.Tl()};
g.h.isActive=function(){return this.g.isActive()};
g.h.rf=function(a){this.g.rf(a)};g.h=Q6.prototype;g.h.Kk=null;g.h.Wd=null;g.h.wc=null;g.h.sr=null;g.h.Bn=null;g.h.Ew=null;g.h.Qn=null;g.h.Fl=0;g.h.BO=0;g.h.qd=null;g.h.Zg=null;g.h.pg=null;g.h.Wh=null;g.h.Xg=null;g.h.Fp=null;g.h.Kj=-1;g.h.uz=-1;g.h.Kf=-1;g.h.oj=0;g.h.cj=0;g.h.Uh=8;var X6=new g.Df;g.A(BBa,g.bf);g.A(CBa,g.bf);g.A(DBa,g.bf);g.h=Q6.prototype;g.h.connect=function(a,b,c,d,e){F6(0);this.sr=b;this.Kk=c||{};d&&g.t(e)&&(this.Kk.OSID=d,this.Kk.OAID=e);this.C?(K6((0,g.z)(this.bx,this,a),100),HBa(this)):this.bx(a)};
g.h.bx=function(a){this.Xg=new yBa(this);this.Xg.tr=null;this.Xg.l=this.B;this.Xg.connect(a)};
g.h.ty=function(){return 0==this.g};
g.h.kC=function(a){this.Zg=null;KBa(this,a)};
g.h.jC=function(){this.pg=null;this.wc=new B6(this,this.o,"rpc",this.D);this.wc.ii=null;this.wc.wr=0;var a=this.Ew.clone();g.Jm(a,"RID","rpc");g.Jm(a,"SID",this.o);g.Jm(a,"CI",this.Fp?"0":"1");g.Jm(a,"AID",this.Kj);R6(this,a);if(!g.vd||g.qc(10))g.Jm(a,"TYPE","xmlhttp"),C6(this.wc,a,!0,this.Qn,!1);else{g.Jm(a,"TYPE","html");var b=this.wc,c=!!this.Qn;b.vj=3;b.ih=d6(a.clone());uBa(b,c)}};
g.h.fC=function(a,b){if(0!=this.g&&(this.wc==a||this.Wd==a))if(this.Kf=a.Zk,this.Wd==a&&3==this.g)if(7<this.Uh){try{var c=this.B.parse(b)}catch(f){c=null}if(g.za(c)&&3==c.length)if(0==c[0])a:{if(!this.pg){if(this.wc)if(this.wc.bk+3E3<this.Wd.bk)T6(this),this.wc.cancel(),this.wc=null;else break a;V6(this);F6(19)}}else this.uz=c[1],0<this.uz-this.Kj&&37500>c[2]&&this.Fp&&0==this.cj&&!this.Wh&&(this.Wh=K6((0,g.z)(this.eP,this),6E3));else W6(this,11)}else b!=fDa.CX.g&&W6(this,11);else if(this.wc==a&&
T6(this),!g.E(b)){c=this.B.parse(b);g.za(c);for(var d=0;d<c.length;d++){var e=c[d];this.Kj=e[0];e=e[1];2==this.g?"c"==e[0]?(this.o=e[1],this.Qn=e[2],e=e[3],null!=e?this.Uh=e:this.Uh=6,this.g=3,this.qd&&this.qd.Qw(),this.Ew=N6(this,this.Tl()?this.Qn:null,this.sr),LBa(this)):"stop"==e[0]&&W6(this,7):3==this.g&&("stop"==e[0]?W6(this,7):"noop"!=e[0]&&this.qd&&this.qd.Pw(e),this.cj=0)}}};
g.h.eP=function(){null!=this.Wh&&(this.Wh=null,this.wc.cancel(),this.wc=null,V6(this),F6(20))};
g.h.Jo=function(a){if(this.wc==a){T6(this);this.wc=null;var b=2}else if(this.Wd==a)this.Wd=null,b=1;else return;this.Kf=a.Zk;if(0!=this.g)if(a.xf)1==b?(b=(0,g.G)()-a.bk,X6.dispatchEvent(new CBa(X6,a.Ii?a.Ii.length:0,b,this.oj)),S6(this),this.A.length=0):LBa(this);else{var c=a.jh,d;if(!(d=3==c||7==c||0==c&&0<this.Kf)){if(d=1==b)this.Wd||this.Zg||1==this.g||2<=this.oj?d=!1:(this.Zg=K6((0,g.z)(this.kC,this,a),MBa(this,this.oj)),this.oj++,d=!0);d=!(d||2==b&&V6(this))}if(d)switch(c){case 1:W6(this,5);
break;case 4:W6(this,10);break;case 3:W6(this,6);break;case 7:W6(this,12);break;default:W6(this,2)}}};
g.h.hI=function(a){if(!g.D(arguments,this.g))throw Error("Unexpected channel state: "+this.g);};
g.h.xU=function(a){a?F6(2):(F6(1),NBa(this,8))};
g.h.Pq=function(a){if(a)throw Error("Can't create secondary domain capable XhrIo object.");a=new g.dx;a.F=!1;return a};
g.h.isActive=function(){return!!this.qd&&this.qd.isActive(this)};
g.h.rf=function(a){X6.dispatchEvent(new DBa(X6,a))};
g.h.Tl=function(){return!(!g.vd||g.qc(10))};
g.h=OBa.prototype;g.h.Qw=function(){};
g.h.Pw=function(){};
g.h.Ow=function(){};
g.h.Eq=function(){};
g.h.Wx=function(){return{}};
g.h.isActive=function(){return!0};g.A(Y6,g.L);g.h=Y6.prototype;g.h.BS=function(){this.cd=Math.min(3E5,2*this.cd);this.o();this.l&&this.start()};
g.h.start=function(){var a=this.cd+15E3*Math.random();g.$t(this.g,a);this.l=(0,g.G)()+a};
g.h.stop=function(){this.g.stop();this.l=0};
g.h.isActive=function(){return this.g.isActive()};
g.h.reset=function(){this.g.stop();this.cd=5E3};g.A(Z6,OBa);g.h=Z6.prototype;g.h.subscribe=function(a,b,c){return this.o.subscribe(a,b,c)};
g.h.unsubscribe=function(a,b,c){return this.o.unsubscribe(a,b,c)};
g.h.Md=function(a){return this.o.Md(a)};
g.h.R=function(a,b){return this.o.R.apply(this.o,arguments)};
g.h.dispose=function(){this.I||(this.I=!0,g.$e(this.o),RBa(this),g.$e(this.l),this.l=null)};
g.h.ha=function(){return this.I};
g.h.connect=function(a,b,c){if(!this.g||2!=this.g.g){this.H="";this.l.stop();this.B=a||null;this.A=b||0;a=this.K+"/test";b=this.K+"/bind";var d=new Q6(c?c.firstTestResults:null,c?c.secondTestResults:null,this.M),e=this.g;e&&(e.qd=null);d.qd=this;this.g=d;e?this.g.connect(a,b,this.C,e.o,e.Kj):c?this.g.connect(a,b,this.C,c.sessionId,c.arrayId):this.g.connect(a,b,this.C)}};
g.h.sendMessage=function(a,b){var c={_sc:a};b&&g.dc(c,b);this.l.isActive()||2==(this.g?this.g.g:0)?this.D.push(c):$6(this)&&IBa(this.g,c)};
g.h.Qw=function(){this.l.reset();this.B=null;this.A=0;if(this.D.length){var a=this.D;this.D=[];for(var b=0,c=a.length;b<c;++b)IBa(this.g,a[b])}this.R("handlerOpened")};
g.h.Ow=function(a){var b=2==a&&401==this.g.Kf;4==a||b||this.l.start();this.R("handlerError",a)};
g.h.Eq=function(a){if(!this.l.isActive())this.R("handlerClosed");else if(a)for(var b=0,c=a.length;b<c;++b){var d=a[b].map;d&&this.D.push(d)}};
g.h.Wx=function(){var a={v:2};this.H&&(a.gsessionid=this.H);0!=this.A&&(a.ui=""+this.A);0!=this.F&&(a.ui=""+this.F);this.B&&g.dc(a,this.B);return a};
g.h.Pw=function(a){"S"==a[0]?this.H=a[1]:"gracefulReconnect"==a[0]?(this.l.start(),GBa(this.g)):this.R("handlerMessage",new PBa(a[0],a[1]))};
g.h.cV=function(){this.l.isActive();var a=this.g,b=0;a.wc&&b++;a.Wd&&b++;0!=b||this.connect(this.B,this.A)};a7.prototype.A=function(a,b,c,d){b?a(d):a({text:c.responseText})};
a7.prototype.o=function(a,b){a(Error("Request error: "+b.status))};
a7.prototype.B=function(a){a(Error("request timed out"))};var ZBa=(0,g.G)(),d7=null,g7=Array(50),f7=-1,h7=!1;g.A(i7,g.KF);i7.prototype.ne=function(){return this.g};
i7.prototype.contains=function(a){return!!l6(this.g,a)};
i7.prototype.get=function(a){return a?m6(this.g,a):null};
i7.prototype.info=function(a){e7(this.D,a)};g.A(j7,g.KF);var gDa=[2E3,2E3,1E3,1E3,1E3,2E3,2E3,5E3,5E3,1E4];g.h=j7.prototype;g.h.start=function(){!this.g&&(0,window.isNaN)(this.xa)&&this.uE()};
g.h.stop=function(){this.g&&(this.g.abort(),this.g=null);(0,window.isNaN)(this.xa)||(g.XD(this.xa),this.xa=window.NaN)};
g.h.V=function(){this.stop();j7.Z.V.call(this)};
g.h.uE=function(){this.xa=window.NaN;this.g=g.sE(b7(this.C,"/pairing/get_screen"),{method:"POST",Lb:{pairing_code:this.B},timeout:5E3,Hb:(0,g.z)(this.eV,this),onError:(0,g.z)(this.dV,this),wd:(0,g.z)(this.fV,this)})};
g.h.eV=function(a,b){this.g=null;var c=b.screen||{};c.dialId=this.o;c.name=this.A;this.R("pairingComplete",new g6(c))};
g.h.dV=function(a){this.g=null;a.status&&404==a.status?this.l>=gDa.length?this.R("pairingFailed",Error("DIAL polling timed out")):(a=gDa[this.l],this.xa=g.VD((0,g.z)(this.uE,this),a),this.l++):this.R("pairingFailed",Error("Server error "+a.status))};
g.h.fV=function(){this.g=null;this.R("pairingFailed",Error("Server not responding"))};g.A(l7,i7);g.h=l7.prototype;g.h.start=function(){k7(this)&&this.R("screenChange");!g.RG("yt-remote-lounge-token-expiration")&&cCa(this);g.XD(this.l);this.l=g.VD((0,g.z)(this.start,this),1E4)};
g.h.add=function(a,b){k7(this);$Ba(this,a);m7(this,!1);this.R("screenChange");b(a);a.token||cCa(this)};
g.h.remove=function(a,b){var c=k7(this);bCa(this,a)&&(m7(this,!1),c=!0);b(a);c&&this.R("screenChange")};
g.h.Bp=function(a,b,c,d){var e=k7(this),f=this.get(a.id);f?(f.name!=b&&(f.name=b,m7(this,!1),e=!0),c(a)):d(Error("no such local screen."));e&&this.R("screenChange")};
g.h.V=function(){g.XD(this.l);l7.Z.V.call(this)};
g.h.NI=function(a){k7(this);var b=this.g.length;a=a&&a.screens||[];for(var c=0,d=a.length;c<d;++c){var e=a[c],f=this.get(e.screenId);f&&(f.token=e.loungeToken,--b)}m7(this,!b);b&&e7(this.D,"Missed "+b+" lounge tokens.")};
g.h.MI=function(a){e7(this.D,"Requesting lounge tokens failed: "+a)};g.A(o7,g.KF);g.h=o7.prototype;g.h.start=function(){var a=(0,window.parseInt)(g.RG("yt-remote-fast-check-period")||"0",10);(this.A=(0,g.G)()-144E5<a?0:a)?q7(this):(this.A=(0,g.G)()+3E5,g.QG("yt-remote-fast-check-period",this.A),this.pu())};
g.h.isEmpty=function(){return g.Xb(this.g)};
g.h.update=function(){n7("Updating availability on schedule.");var a=this.C(),b=g.Lb(this.g,function(b,d){return b&&!!m6(a,d)},this);
p7(this,b)};
g.h.V=function(){g.XD(this.o);this.o=window.NaN;this.l&&(this.l.abort(),this.l=null);o7.Z.V.call(this)};
g.h.pu=function(){g.XD(this.o);this.o=window.NaN;this.l&&this.l.abort();var a=fCa(this);if(g.Pb(a)){var b=b7(this.B,"/pairing/get_screen_availability");this.l=c7(this.B,b,{lounge_token:g.Rb(a).join(",")},(0,g.z)(this.jS,this,a),(0,g.z)(this.iS,this))}else p7(this,{}),q7(this)};
g.h.jS=function(a,b){this.l=null;var c=g.Rb(fCa(this));if(g.ib(c,g.Rb(a))){c=b.screens||[];for(var d={},e=0,f=c.length;e<f;++e)d[a[c[e].loungeToken]]="online"==c[e].status;p7(this,d);q7(this)}else this.hc("Changing Screen set during request."),this.pu()};
g.h.iS=function(a){this.hc("Screen availability failed: "+a);this.l=null;q7(this)};
g.h.hc=function(a){e7("OnlineScreenService",a)};g.A(r7,i7);g.h=r7.prototype;g.h.start=function(){this.o.start();this.l.start();this.g.length&&(this.R("screenChange"),this.l.isEmpty()||this.R("onlineScreenChange"))};
g.h.add=function(a,b,c){this.o.add(a,b,c)};
g.h.remove=function(a,b,c){this.o.remove(a,b,c);this.l.update()};
g.h.Bp=function(a,b,c,d){this.o.contains(a)?this.o.Bp(a,b,c,d):(a="Updating name of unknown screen: "+a.name,e7(this.D,a),d(Error(a)))};
g.h.ne=function(a){return a?this.g:g.Va(this.g,(0,g.Id)(this.A,function(a){return!this.contains(a)},this))};
g.h.vE=function(){return(0,g.Id)(this.ne(!0),function(a){return!!this.l.g[a.id]},this)};
g.h.wE=function(a,b,c,d,e){this.info("getDialScreenByPairingCode "+a+" / "+b);var f=new j7(this.C,a,b,c);f.subscribe("pairingComplete",(0,g.z)(function(a){g.$e(f);d(s7(this,a))},this));
f.subscribe("pairingFailed",function(a){g.$e(f);e(a)});
f.start();return(0,g.z)(f.stop,f)};
g.h.hV=function(a,b,c,d){g.sE(b7(this.C,"/pairing/get_screen"),{method:"POST",Lb:{pairing_code:a},timeout:5E3,Hb:(0,g.z)(function(a,d){var e=new g6(d.screen||{});if(!e.name||jCa(this,e.name)){a:{var f=e.name;for(var m=2,n=b(f,m);jCa(this,n);){m++;if(20<m)break a;n=b(f,m)}f=n}e.name=f}c(s7(this,e))},this),
onError:(0,g.z)(function(a){d(Error("pairing request failed: "+a.status))},this),
wd:(0,g.z)(function(){d(Error("pairing request timed out."))},this)})};
g.h.V=function(){g.$e(this.o);g.$e(this.l);r7.Z.V.call(this)};
g.h.eJ=function(){kCa(this);this.R("screenChange");this.l.update()};
r7.prototype.dispose=r7.prototype.dispose;g.A(u7,g.KF);g.h=u7.prototype;g.h.Ko=function(a){this.o=a;this.R("sessionScreen",this.o)};
g.h.te=function(a){this.ha()||(a&&v7(this,""+a),this.o=null,this.R("sessionScreen",null))};
g.h.info=function(a){e7(this.M,a)};
g.h.yE=function(){return null};
g.h.zu=function(a){var b=this.l;a?(b.displayStatus=new window.chrome.cast.ReceiverDisplayStatus(a,[]),b.displayStatus.showStop=!0):b.displayStatus=null;window.chrome.cast.setReceiverDisplayStatus(b,(0,g.z)(function(){this.info("Updated receiver status for "+b.friendlyName+": "+a)},this),(0,g.z)(function(){v7(this,"Failed to update receiver status for: "+b.friendlyName)},this))};
g.h.V=function(){this.zu("");u7.Z.V.call(this)};g.A(w7,u7);g.h=w7.prototype;g.h.yu=function(a){if(this.g){if(this.g==a)return;v7(this,"Overriding cast sesison with new session object");this.g.removeUpdateListener(this.C);this.g.removeMessageListener("urn:x-cast:com.google.youtube.mdx",this.B)}this.g=a;this.g.addUpdateListener(this.C);this.g.addMessageListener("urn:x-cast:com.google.youtube.mdx",this.B);mCa(this)};
g.h.Lj=function(a){this.info("launchWithParams no-op for Cast: "+g.yg(a))};
g.h.stop=function(){this.g?this.g.stop((0,g.z)(function(){this.te()},this),(0,g.z)(function(){this.te(Error("Failed to stop receiver app."))},this)):this.te(Error("Stopping cast device witout session."))};
g.h.zu=g.y;g.h.V=function(){this.info("disposeInternal");g.XD(this.A);this.A=0;this.g&&(this.g.removeUpdateListener(this.C),this.g.removeMessageListener("urn:x-cast:com.google.youtube.mdx",this.B));this.g=null;w7.Z.V.call(this)};
g.h.mT=function(a,b){if(!this.ha())if(b){var c=g.Yw(b);if(g.Ca(c)){var d=""+c.type;c=c.data||{};this.info("onYoutubeMessage_: "+d+" "+g.yg(c));switch(d){case "mdxSessionStatus":lCa(this,c.screenId);break;default:v7(this,"Unknown youtube message: "+d)}}else v7(this,"Unable to parse message.")}else v7(this,"No data in message.")};
g.h.jy=function(a,b,c,d){iCa(this.H,this.l.label,a,this.l.friendlyName,(0,g.z)(function(e){e?b(e):0<=d?(v7(this,"Screen "+a+" appears to be offline. "+d+" retries left."),g.VD((0,g.z)(this.jy,this,a,b,c,d-1),300)):c(Error("Unable to fetch screen."))},this),c)};
g.h.yE=function(){return this.g};
g.h.iV=function(a){this.ha()||a||(v7(this,"Cast session died."),this.te())};g.A(x7,u7);g.h=x7.prototype;g.h.yu=function(a){this.A=a;this.A.addUpdateListener(this.K)};
g.h.Lj=function(a){this.B=a;this.D()};
g.h.stop=function(){this.g();this.g=g.y;g.XD(this.C);this.A?this.A.stop((0,g.z)(this.te,this,null),(0,g.z)(this.te,this,"Failed to stop DIAL device.")):this.te()};
g.h.V=function(){this.g();this.g=g.y;g.XD(this.C);this.A&&this.A.removeUpdateListener(this.K);this.A=null;x7.Z.V.call(this)};
g.h.lV=function(a){this.ha()||a||(v7(this,"DIAL session died."),this.g(),this.g=g.y,this.te())};
g.h.hs=function(a){this.I=k6();if(this.B){var b=new window.chrome.cast.DialLaunchResponse(!0,oCa(this));a(b);nCa(this)}else this.D=(0,g.z)(function(){g.XD(this.C);this.D=g.y;this.C=window.NaN;var b=new window.chrome.cast.DialLaunchResponse(!0,oCa(this));a(b);nCa(this)},this),this.C=g.VD((0,g.z)(function(){this.D()},this),100)};
g.h.rK=function(a,b,c){iCa(this.H,this.F.receiver.label,a,this.l.friendlyName,(0,g.z)(function(a){a&&a.token?(this.Ko(a),b(new window.chrome.cast.DialLaunchResponse(!1))):this.hs(b,c)},this),(0,g.z)(function(a){v7(this,"Failed to get DIAL screen: "+a);
this.hs(b,c)},this))};g.A(y7,u7);y7.prototype.stop=function(){this.te()};
y7.prototype.yu=g.y;y7.prototype.Lj=function(){g.XD(this.g);this.g=window.NaN;var a=m6(this.H.ne(),this.l.label);a?this.Ko(a):this.te(Error("No such screen"))};
y7.prototype.V=function(){g.XD(this.g);this.g=window.NaN;y7.Z.V.call(this)};g.A(z7,g.KF);g.h=z7.prototype;
g.h.init=function(a,b){window.chrome.cast.timeout.requestSession=3E4;var c=new window.chrome.cast.SessionRequest(this.D);this.F||(c.dialRequest=new window.chrome.cast.DialRequest("YouTube"));var d=window.chrome.cast.AutoJoinPolicy.TAB_AND_ORIGIN_SCOPED,e=a?window.chrome.cast.DefaultActionPolicy.CAST_THIS_TAB:window.chrome.cast.DefaultActionPolicy.CREATE_SESSION;c=new window.chrome.cast.ApiConfig(c,(0,g.z)(this.gC,this),(0,g.z)(this.TR,this),d,e);c.customDialLaunchCallback=(0,g.z)(this.PP,this);window.chrome.cast.initialize(c,
(0,g.z)(function(){this.ha()||(window.chrome.cast.addReceiverActionListener(this.A),WBa(),this.l.subscribe("onlineScreenChange",(0,g.z)(this.xE,this)),this.o=qCa(this),window.chrome.cast.setCustomReceivers(this.o,g.y,(0,g.z)(function(a){this.hc("Failed to set initial custom receivers: "+g.yg(a))},this)),this.R("yt-remote-cast2-availability-change",B7(this)),b(!0))},this),(0,g.z)(function(a){this.hc("Failed to initialize API: "+g.yg(a));
b(!1)},this))};
g.h.gU=function(a,b){A7("Setting connected screen ID: "+a+" -> "+b);if(this.g){var c=this.g.o;if(!a||c&&c.id!=a)A7("Unsetting old screen status: "+this.g.l.friendlyName),C7(this,null)}if(a&&b){if(!this.g){c=m6(this.l.ne(),a);if(!c){A7("setConnectedScreenStatus: Unknown screen.");return}var d=pCa(this,c);d||(A7("setConnectedScreenStatus: Connected receiver not custom..."),d=new window.chrome.cast.Receiver(c.uuid?c.uuid:c.id,c.name),d.receiverType=window.chrome.cast.ReceiverType.CUSTOM,this.o.push(d),
window.chrome.cast.setCustomReceivers(this.o,g.y,(0,g.z)(function(a){this.hc("Failed to set initial custom receivers: "+g.yg(a))},this)));
A7("setConnectedScreenStatus: new active receiver: "+d.friendlyName);C7(this,new y7(this.l,d),!0)}this.g.zu(b)}else A7("setConnectedScreenStatus: no screen.")};
g.h.hU=function(a){this.ha()?this.hc("Setting connection data on disposed cast v2"):this.g?this.g.Lj(a):this.hc("Setting connection data without a session")};
g.h.kV=function(){this.ha()?this.hc("Stopping session on disposed cast v2"):this.g?(this.g.stop(),C7(this,null)):A7("Stopping non-existing session")};
g.h.requestSession=function(){window.chrome.cast.requestSession((0,g.z)(this.gC,this),(0,g.z)(this.oS,this))};
g.h.V=function(){this.l.unsubscribe("onlineScreenChange",(0,g.z)(this.xE,this));window.chrome&&window.chrome.cast&&window.chrome.cast.removeReceiverActionListener(this.A);g.Ta(g.x("yt.mdx.remote.debug.handlers_")||[],TBa);g.$e(this.g);z7.Z.V.call(this)};
g.h.hc=function(a){e7("Controller",a)};
g.h.hC=function(a,b){this.g==a&&(b||C7(this,null),this.R("yt-remote-cast2-session-change",b))};
g.h.PR=function(a,b){if(!this.ha())if(a)switch(a.friendlyName=window.chrome.cast.unescape(a.friendlyName),A7("onReceiverAction_ "+a.label+" / "+a.friendlyName+"-- "+b),b){case window.chrome.cast.ReceiverAction.CAST:if(this.g)if(this.g.l.label!=a.label)A7("onReceiverAction_: Stopping active receiver: "+this.g.l.friendlyName),this.g.stop();else{A7("onReceiverAction_: Casting to active receiver.");this.g.o&&this.R("yt-remote-cast2-session-change",this.g.o);break}switch(a.receiverType){case window.chrome.cast.ReceiverType.CUSTOM:C7(this,
new y7(this.l,a));break;case window.chrome.cast.ReceiverType.DIAL:C7(this,new x7(this.l,a,this.C));break;case window.chrome.cast.ReceiverType.CAST:C7(this,new w7(this.l,a));break;default:this.hc("Unknown receiver type: "+a.receiverType)}break;case window.chrome.cast.ReceiverAction.STOP:this.g&&this.g.l.label==a.label?this.g.stop():this.hc("Stopping receiver w/o session: "+a.friendlyName)}else this.hc("onReceiverAction_ called without receiver.")};
g.h.PP=function(a){if(this.ha())return window.Promise.reject(Error("disposed"));var b=a.receiver;b.receiverType!=window.chrome.cast.ReceiverType.DIAL&&(this.hc("Not DIAL receiver: "+b.friendlyName),b.receiverType=window.chrome.cast.ReceiverType.DIAL);var c=this.g?this.g.l:null;if(!c||c.label!=b.label)return this.hc("Receiving DIAL launch request for non-clicked DIAL receiver: "+b.friendlyName),window.Promise.reject(Error("illegal DIAL launch"));if(c&&c.label==b.label&&c.receiverType!=window.chrome.cast.ReceiverType.DIAL){if(this.g.o)return A7("Reselecting dial screen."),
this.R("yt-remote-cast2-session-change",this.g.o),window.Promise.resolve(new window.chrome.cast.DialLaunchResponse(!1));this.hc('Changing CAST intent from "'+c.receiverType+'" to "dial" for '+b.friendlyName);C7(this,new x7(this.l,b,this.C))}b=this.g;b.F=a;return b.F.appState==window.chrome.cast.DialAppState.RUNNING?new window.Promise((0,g.z)(b.rK,b,(b.F.extraData||{}).screenId||null)):new window.Promise((0,g.z)(b.hs,b))};
g.h.gC=function(a){if(!this.ha()){A7("New cast session ID: "+a.sessionId);var b=a.receiver;if(b.receiverType!=window.chrome.cast.ReceiverType.CUSTOM){if(!this.g)if(b.receiverType==window.chrome.cast.ReceiverType.CAST)A7("Got resumed cast session before resumed mdx connection."),b.friendlyName=window.chrome.cast.unescape(b.friendlyName),C7(this,new w7(this.l,b),!0);else{this.hc("Got non-cast session without previous mdx receiver event, or mdx resume.");return}var c=this.g.l,d=m6(this.l.ne(),c.label);
d&&h6(d,b.label)&&c.receiverType!=window.chrome.cast.ReceiverType.CAST&&b.receiverType==window.chrome.cast.ReceiverType.CAST&&(A7("onSessionEstablished_: manual to cast session change "+b.friendlyName),g.$e(this.g),this.g=new w7(this.l,b),this.g.subscribe("sessionScreen",(0,g.z)(this.hC,this,this.g)),this.g.Lj(null));this.g.yu(a)}}};
g.h.jV=function(){return this.g?this.g.yE():null};
g.h.oS=function(a){this.ha()||(this.hc("Failed to estabilish a session: "+g.yg(a)),a.code!=window.chrome.cast.ErrorCode.CANCEL&&C7(this,null))};
g.h.TR=function(a){A7("Receiver availability updated: "+a);if(!this.ha()){var b=B7(this);this.B=a==window.chrome.cast.ReceiverAvailability.AVAILABLE;B7(this)!=b&&this.R("yt-remote-cast2-availability-change",B7(this))}};
g.h.xE=function(){this.ha()||(this.o=qCa(this),A7("Updating custom receivers: "+g.yg(this.o)),window.chrome.cast.setCustomReceivers(this.o,g.y,(0,g.z)(function(){this.hc("Failed to set custom receivers.")},this)),this.R("yt-remote-cast2-availability-change",B7(this)))};
z7.prototype.setLaunchParams=z7.prototype.hU;z7.prototype.setConnectedScreenStatus=z7.prototype.gU;z7.prototype.stopSession=z7.prototype.kV;z7.prototype.getCastSession=z7.prototype.jV;z7.prototype.requestSession=z7.prototype.requestSession;z7.prototype.init=z7.prototype.init;z7.prototype.dispose=z7.prototype.dispose;var I7=[];g.h=N7.prototype;
g.h.reset=function(a){this.listId="";this.index=-1;this.videoId="";O7(this);this.volume=-1;this.muted=!1;a&&(this.index=a.index,this.listId=a.listId,this.videoId=a.videoId,this.g=a.playerState,this.volume=a.volume,this.muted=a.muted,this.audioTrackId=a.audioTrackId,this.l=a.trackData,this.Nf=a.hasPrevious,this.hasNext=a.hasNext,this.F=a.playerTime,this.D=a.playerTimeAt,this.B=a.seekableStart,this.o=a.seekableEnd,this.H=a.duration,this.I=a.loadedTime,this.A=a.liveIngestionTime,this.C=!(0,window.isNaN)(this.A))};
g.h.kb=function(){return 1==this.g};
g.h.isAdPlaying=function(){return 1081==this.g};
g.h.getDuration=function(){return this.C?this.H+P7(this):this.H};
g.h.clone=function(){return new N7(T7(this))};g.A(V7,g.KF);g.h=V7.prototype;g.h.play=function(){1==this.g?(this.l?this.l.play(null,g.y,a8(this,"play")):$7(this,"play"),Z7(this,1,R7(W7(this))),this.R("remotePlayerChange")):X7(this,this.play)};
g.h.pause=function(){1==this.g?(this.l?this.l.pause(null,g.y,a8(this,"pause")):$7(this,"pause"),Z7(this,2,R7(W7(this))),this.R("remotePlayerChange")):X7(this,this.pause)};
g.h.tE=function(a){if(1==this.g){if(this.l){var b=W7(this),c=new window.chrome.cast.media.SeekRequest;c.currentTime=a;c.resumeState=b.kb()||3==b.g?window.chrome.cast.media.ResumeState.PLAYBACK_START:window.chrome.cast.media.ResumeState.PLAYBACK_PAUSE;this.l.seek(c,g.y,a8(this,"seekTo",{newTime:a}))}else $7(this,"seekTo",{newTime:a});Z7(this,3,a);this.R("remotePlayerChange")}else X7(this,g.Fa(this.tE,a))};
g.h.stop=function(){if(1==this.g){this.l?this.l.stop(null,g.y,a8(this,"stopVideo")):$7(this,"stopVideo");var a=W7(this);a.index=-1;a.videoId="";O7(a);Y7(this,a);this.R("remotePlayerChange")}else X7(this,this.stop)};
g.h.setVolume=function(a,b){if(1==this.g){var c=W7(this);if(this.o){if(c.volume!=a){var d=Math.round(a)/100;this.o.setReceiverVolumeLevel(d,(0,g.z)(function(){e7("CP","set receiver volume: "+d)},this),(0,g.z)(function(){this.hc("failed to set receiver volume.")},this))}c.muted!=b&&this.o.setReceiverMuted(b,(0,g.z)(function(){e7("CP","set receiver muted: "+b)},this),(0,g.z)(function(){this.hc("failed to set receiver muted.")},this))}else{var e={volume:a,
muted:b};-1!=c.volume&&(e.delta=a-c.volume);$7(this,"setVolume",e)}c.muted=b;c.volume=a;Y7(this,c)}else X7(this,g.Fa(this.setVolume,a,b))};
g.h.sD=function(a,b){if(1==this.g){var c=W7(this),d={videoId:a};b&&(c.l={trackName:b.name,languageCode:b.languageCode,sourceLanguageCode:b.translationLanguage?b.translationLanguage.languageCode:"",languageName:b.languageName,format:b.format,kind:b.kind},d.style=g.yg(b.style),g.dc(d,c.l));$7(this,"setSubtitlesTrack",d);Y7(this,c)}else X7(this,g.Fa(this.sD,a,b))};
g.h.rv=function(a,b){if(1==this.g){$7(this,"setAudioTrack",{videoId:a,audioTrackId:b.Pb.id});var c=W7(this);c.audioTrackId=b.Pb.id;Y7(this,c)}else X7(this,g.Fa(this.rv,a,b))};
g.h.sE=function(a,b){if(1==this.g){if(a&&b){var c=W7(this);S7(c,a,b);Y7(this,c)}$7(this,"previous")}else X7(this,g.Fa(this.sE,a,b))};
g.h.rE=function(a,b){if(1==this.g){if(a&&b){var c=W7(this);S7(c,a,b);Y7(this,c)}$7(this,"next")}else X7(this,g.Fa(this.rE,a,b))};
g.h.Ax=function(){1==this.g?$7(this,"dismissAutoplay"):X7(this,this.Ax)};
g.h.dispose=function(){if(3!=this.g){var a=this.g;this.g=3;this.R("proxyStateChange",a,this.g)}V7.Z.dispose.call(this)};
g.h.V=function(){DCa(this);this.A=null;this.B.clear();U7(this,null);V7.Z.V.call(this)};
g.h.tv=function(a){if((a!=this.g||2==a)&&3!=this.g&&0!=a){var b=this.g;this.g=a;this.R("proxyStateChange",b,a);if(1==a)for(;!this.B.isEmpty();)g.oC(this.B).apply(this);else 3==a&&this.dispose()}};
g.h.LR=function(a,b){this.R(a,b)};
g.h.lP=function(a){if(!a)this.Il(null),U7(this,null);else if(this.o.receiver.volume){a=this.o.receiver.volume;var b=W7(this),c=Math.round(100*a.level||0);if(b.volume!=c||b.muted!=a.muted)e7("CP","Cast volume update: "+a.level+(a.muted?" muted":"")),b.volume=c,b.muted=!!a.muted,Y7(this,b)}};
g.h.Il=function(a){e7("CP","Cast media: "+!!a);this.l&&this.l.removeUpdateListener(this.F);if(this.l=a)this.l.addUpdateListener(this.F),ECa(this),this.R("remotePlayerChange")};
g.h.kP=function(a){a?(ECa(this),this.R("remotePlayerChange")):this.Il(null)};
g.h.yP=function(){var a=ACa();a&&U7(this,a)};
g.h.hc=function(a){e7("CP",a)};g.A(b8,g.KF);g.h=b8.prototype;
g.h.connect=function(a,b){if(b){var c=b.listId,d=b.videoId,e=b.playerParams,f=b.clickTrackingParams,k=b.index,l={videoId:d},m=b.currentTime;g.t(m)&&(l.currentTime=5>=m?0:m);e&&(l.playerParams=e);f&&(l.clickTrackingParams=f);c&&(l.listId=c);g.t(k)&&(l.currentIndex=k);c&&(this.Za.listId=c);this.Za.videoId=d;this.Za.index=k||0;this.Za.state=3;Q7(this.Za,m);this.A="UNSUPPORTED";c8("Connecting with setPlaylist and params: "+g.yg(l));this.g.connect({method:"setPlaylist",params:g.yg(l)},a,$Aa())}else c8("Connecting without params"),
this.g.connect({},a,$Aa());GCa(this)};
g.h.dispose=function(){this.ha()||(this.R("beforeDispose"),d8(this,3));b8.Z.dispose.call(this)};
g.h.V=function(){e8(this);g8(this);f8(this);g.XD(this.H);this.H=window.NaN;g.XD(this.I);this.I=window.NaN;this.o=null;g.vF(this.P);this.P.length=0;this.g.dispose();b8.Z.V.call(this);this.A=this.D=this.l=this.Za=this.g=null};
g.h.EI=function(){this.C(2)};
g.h.pP=function(){c8("Channel opened");this.N&&(this.N=!1,f8(this),this.M=g.VD((0,g.z)(function(){c8("Timing out waiting for a screen.");this.C(1)},this),15E3));
dBa(QBa(this.g),this.X)};
g.h.mP=function(){c8("Channel closed");(0,window.isNaN)(this.B)?r6(!0):r6();this.dispose()};
g.h.nP=function(a){r6();(0,window.isNaN)(this.F())?(c8("Channel error: "+a+" without reconnection"),this.dispose()):(this.N=!0,c8("Channel error: "+a+" with reconnection in "+this.F()+" ms"),d8(this,2))};
g.h.oP=function(a){a.params?c8("Received: action="+a.action+", params="+g.yg(a.params)):c8("Received: action="+a.action+" {}");switch(a.action){case "loungeStatus":a=g.Yw(a.params.devices);this.l=(0,g.I)(a,function(a){return new f6(a)});
a=!!g.La(this.l,function(a){return"LOUNGE_SCREEN"==a.type});
JCa(this,a);break;case "loungeScreenDisconnected":g.Ua(this.l,function(a){return"LOUNGE_SCREEN"==a.type});
JCa(this,!1);break;case "remoteConnected":var b=new f6(g.Yw(a.params.device));g.La(this.l,function(a){return b?a.id==b.id:!1})||g.Ra(this.l,b);
break;case "remoteDisconnected":b=new f6(g.Yw(a.params.device));g.Ua(this.l,function(a){return b?a.id==b.id:!1});
break;case "gracefulDisconnect":break;case "playlistModified":LCa(this,a);break;case "nowPlaying":NCa(this,a);break;case "onStateChange":MCa(this,a);break;case "onAdStateChange":OCa(this,a);break;case "onVolumeChanged":PCa(this,a);break;case "onSubtitlesTrackChanged":KCa(this,a);break;case "nowAutoplaying":QCa(this,a);break;case "autoplayDismissed":this.R("autoplayDismissed");break;case "autoplayUpNext":this.D=a.params.videoId||null;this.R("autoplayUpNext",this.D);break;case "onAutoplayModeChanged":this.A=
a.params.autoplayMode;this.R("autoplayModeChange",this.A);"DISABLED"==this.A&&this.R("autoplayDismissed");break;case "onHasPreviousNextChanged":RCa(this,a);break;case "requestAssistedSignIn":this.R("assistedSignInRequested",a.params.authCode);break;default:c8("Unrecognized action: "+a.action)}};
g.h.PT=function(){if(this.o){var a=this.o;this.o=null;this.Za.videoId!=a&&h8(this,"getNowPlaying")}};
b8.prototype.subscribe=b8.prototype.subscribe;b8.prototype.unsubscribeByKey=b8.prototype.Md;b8.prototype.fa=function(){var a=3;this.ha()||(a=0,(0,window.isNaN)(this.F())?$6(this.g)&&(0,window.isNaN)(this.B)&&(a=1):a=2);return a};
b8.prototype.getProxyState=b8.prototype.fa;b8.prototype.C=function(a){c8("Disconnecting with "+a);e8(this);this.R("beforeDisconnect",a);1==a&&r6();RBa(this.g,a);this.dispose()};
b8.prototype.disconnect=b8.prototype.C;b8.prototype.da=function(){var a=this.Za;this.o&&(a=this.Za.clone(),S7(a,this.o,a.index));return T7(a)};
b8.prototype.getPlayerContextData=b8.prototype.da;
b8.prototype.ma=function(a){var b=new N7(a);b.videoId&&b.videoId!=this.Za.videoId&&(this.o=b.videoId,g.XD(this.H),this.H=g.VD((0,g.z)(this.PT,this),5E3));var c=[];this.Za.listId==b.listId&&this.Za.videoId==b.videoId&&this.Za.index==b.index||c.push("remoteQueueChange");this.Za.g==b.g&&this.Za.volume==b.volume&&this.Za.muted==b.muted&&R7(this.Za)==R7(b)&&g.yg(this.Za.l)==g.yg(b.l)||c.push("remotePlayerChange");this.Za.reset(a);(0,g.B)(c,function(a){this.R(a)},this)};
b8.prototype.setPlayerContextData=b8.prototype.ma;b8.prototype.W=function(){var a=this.g.C.id,b=g.La(this.l,function(b){return"REMOTE_CONTROL"==b.type&&b.id!=a});
return b?b.id:""};
b8.prototype.getOtherConnectedRemoteId=b8.prototype.W;b8.prototype.F=function(){var a=this.g;return a.l.isActive()?a.l.l-(0,g.G)():window.NaN};
b8.prototype.getReconnectTimeout=b8.prototype.F;b8.prototype.Y=function(){return this.A||"UNSUPPORTED"};
b8.prototype.getAutoplayMode=b8.prototype.Y;b8.prototype.ba=function(){return this.D||""};
b8.prototype.getAutoplayVideoId=b8.prototype.ba;b8.prototype.pa=function(){if(!(0,window.isNaN)(this.F())){var a=this.g.l;g.au(a.g);a.start()}};
b8.prototype.reconnect=b8.prototype.pa;b8.prototype.ia=function(a,b){h8(this,a,b);ICa(this)};
b8.prototype.sendMessage=b8.prototype.ia;g.A(i8,i7);g.h=i8.prototype;g.h.ne=function(a){return this.bd.$_gs(a)};
g.h.contains=function(a){return!!this.bd.$_c(a)};
g.h.get=function(a){return this.bd.$_g(a)};
g.h.start=function(){this.bd.$_st()};
g.h.add=function(a,b,c){this.bd.$_a(a,b,c)};
g.h.remove=function(a,b,c){this.bd.$_r(a,b,c)};
g.h.Bp=function(a,b,c,d){this.bd.$_un(a,b,c,d)};
g.h.V=function(){for(var a=0,b=this.l.length;a<b;++a)this.bd.$_ubk(this.l[a]);this.l.length=0;this.bd=null;i8.Z.V.call(this)};
g.h.gV=function(){this.R("screenChange")};
g.h.lR=function(){this.R("onlineScreenChange")};
r7.prototype.$_st=r7.prototype.start;r7.prototype.$_gspc=r7.prototype.hV;r7.prototype.$_gsppc=r7.prototype.wE;r7.prototype.$_c=r7.prototype.contains;r7.prototype.$_g=r7.prototype.get;r7.prototype.$_a=r7.prototype.add;r7.prototype.$_un=r7.prototype.Bp;r7.prototype.$_r=r7.prototype.remove;r7.prototype.$_gs=r7.prototype.ne;r7.prototype.$_gos=r7.prototype.vE;r7.prototype.$_s=r7.prototype.subscribe;r7.prototype.$_ubk=r7.prototype.Md;var j8=null,k8=null,z8=null,o8=[];g.p(A8,g.L);g.h=A8.prototype;
g.h.V=function(){g.L.prototype.V.call(this);this.A.stop();this.B.stop();this.K.stop();this.N();this.g.unsubscribe("proxyStateChange",this.eC,this);this.g.unsubscribe("remotePlayerChange",this.Ll,this);this.g.unsubscribe("remoteQueueChange",this.Lo,this);this.g.unsubscribe("autoplayUpNext",this.AB,this);this.g.unsubscribe("previousNextChange",this.bC,this);this.g.unsubscribe("nowAutoplaying",this.TB,this);this.g.unsubscribe("autoplayDismissed",this.zB,this);this.g=this.F=null};
g.h.CA=function(a,b){for(var c=[],d=1;d<arguments.length;++d)c[d-1]=arguments[d];if(2!=this.g.g)if(D8(this)){if(!W7(this.g).isAdPlaying()||"control_seek"!=a)switch(a){case "control_toggle_play_pause":W7(this.g).kb()?this.g.pause():this.g.play();break;case "control_play":this.g.play();break;case "control_pause":this.g.pause();break;case "control_seek":this.I.tj(c[0],c[1]);break;case "control_subtitles_set_track":E8(this,c[0]);break;case "control_set_audio_track":c=c[0],D8(this)&&this.g.rv(this.l.ea(1).videoId,
c)}}else switch(a){case "control_toggle_play_pause":case "control_play":case "control_pause":c=this.l.getCurrentTime();F8(this,0==c?void 0:c);break;case "control_seek":F8(this,c[0]);break;case "control_subtitles_set_track":E8(this,c[0]);break;case "control_set_audio_track":c=c[0],D8(this)&&this.g.rv(this.l.ea(1).videoId,c)}};
g.h.jP=function(a){this.K.zI(a)};
g.h.JU=function(a){this.CA("control_subtitles_set_track",g.Xb(a)?null:a)};
g.h.ED=function(){var a=this.l.Ac("captions","track");g.Xb(a)||E8(this,a)};
g.h.RB=function(a){if(D8(this)){this.g.unsubscribe("remotePlayerChange",this.Ll,this);var b=Math.round(a.volume);a=!!a.muted;var c=W7(this.g);if(b!=c.volume||a!=c.muted)this.g.setVolume(b,a),this.M.start();this.g.subscribe("remotePlayerChange",this.Ll,this)}};
g.h.DQ=function(){g.Xb(this.C)||cDa(this,this.C);this.D=!1};
g.h.eC=function(a,b){this.B.stop();2==b&&this.BD()};
g.h.Ll=function(){if(D8(this)){this.A.stop();var a=W7(this.g);switch(a.g){case 1081:case 1:C8(this,new g.YO(8));this.AD();break;case 1085:case 3:C8(this,new g.YO(9));break;case 1083:case 0:C8(this,new g.YO(2));this.I.stop();B8(this,this.l.ea().lengthSeconds);break;case 1084:C8(this,new g.YO(4));break;case 2:C8(this,new g.YO(4));B8(this,R7(a));break;case -1:C8(this,new g.YO(64));break;case -1E3:a={errorCode:"mdx.remoteerror",message:g.V("YTP_MDX_PLAYER_ERROR")},C8(this,new g.YO(128,a))}a=W7(this.g).l;
var b=this.C;(a||b?a&&b&&a.trackName==b.trackName&&a.languageCode==b.languageCode&&a.languageName==b.languageName&&a.format==b.format&&a.kind==b.kind:1)||(this.C=a,cDa(this,a));a=W7(this.g);-1==a.volume||Math.round(this.l.getVolume())==a.volume&&this.l.isMuted()==a.muted||this.M.isActive()||this.hE()}else bDa(this)};
g.h.bC=function(){this.l.R("mdxpreviousnextchange")};
g.h.Lo=function(){D8(this)||bDa(this)};
g.h.LH=function(){this.g.Ax()};
g.h.AB=function(a){a&&(a=g.sE("/watch_queue_ajax",{method:"GET",Xc:{action_get_watch_queue_item:1,video_id:a},Hb:(0,g.z)(this.NS,this)}))&&(this.N=(0,g.z)(a.abort,a))};
g.h.NS=function(a,b){var c=new g.YN({videoId:b.videoId,title:b.title,author:b.author,murlmq_webp:b.url});this.suggestion=c;this.l.R("mdxautoplayupnext",c)};
g.h.TB=function(a){(0,window.isNaN)(a)||this.l.R("mdxnowautoplaying",a)};
g.h.zB=function(){this.l.R("mdxautoplaycanceled")};
g.h.nN=function(a,b){-1==W7(this.g).g?F8(this,a):b&&this.g.tE(a)};
g.h.hE=function(){if(D8(this)){var a=W7(this.g);this.o.Ba(this.P);a.muted?this.l.mute():this.l.Yf();this.l.setVolume(a.volume);this.P=this.o.O(this.l,"onVolumeChange",this.RB)}};
g.h.AD=function(){this.A.stop();if(!this.g.ha()){var a=W7(this.g);a.kb()&&C8(this,new g.YO(8));B8(this,R7(a));this.A.start()}};
g.h.BD=function(){this.B.stop();this.A.stop();var a=this.g.A.getReconnectTimeout();2==this.g.g&&!(0,window.isNaN)(a)&&this.B.start()};g.p(G8,g.W);G8.prototype.A=function(a){eDa(this,a.state)};g.p(H8,g.JZ);H8.prototype.I=function(){var a=this.l.Ac("remote","receivers");a&&1<a.length&&!this.l.Ac("remote","quickCast")?(this.F=g.kb(a,this.B,this),g.KZ(this,(0,g.I)(a,this.B)),a=this.l.Ac("remote","currentReceiver"),this.qf(this.B(a)),this.enable(!0)):this.enable(!1)};
H8.prototype.B=function(a){return a.key};
H8.prototype.pf=function(a){return"cast-selector-receiver"==a?g.V("YTP_MDX_CAST_SELECTOR"):this.F[a].name};
H8.prototype.td=function(a){g.JZ.prototype.td.call(this,a);this.l.Jd("remote","currentReceiver",this.F[a]);this.A.Qb()};g.p(I8,g.rV);g.h=I8.prototype;g.h.create=function(){WCa(g.pM(g.Y(this.g)));this.C.push(g.WF("yt-remote-before-disconnect",this.fP,this));this.C.push(g.WF("yt-remote-connection-change",this.UR,this));this.C.push(g.WF("yt-remote-receiver-availability-change",this.cC,this));this.C.push(g.WF("yt-remote-auto-connect",this.SR,this));this.C.push(g.WF("yt-remote-receiver-resumed",this.RR,this));this.cC()};
g.h.load=function(){this.g.jt();g.rV.prototype.load.call(this);this.B=new A8(this,this.g,this.l);var a=(a=aDa())?a.currentTime:0;var b=y8()?new V7(t8(),void 0):null;0==a&&b&&(a=R7(W7(b)));0!=a&&(this.H=a||0,this.g.R("progresssync",a,void 0));dDa(this,this.D,this.D);g.V_(this.g.app,6)};
g.h.unload=function(){this.g.R("mdxautoplaycanceled");this.A=this.o;g.af(this.B,this.l);this.l=this.B=null;g.rV.prototype.unload.call(this);g.V_(this.g.app,5)};
g.h.V=function(){g.XF(this.C);g.rV.prototype.V.call(this)};
g.h.Al=function(a,b){for(var c=[],d=1;d<arguments.length;++d)c[d-1]=arguments[d];this.loaded&&this.B.CA.apply(this.B,[].concat([a],g.qa(c)))};
g.h.vI=function(){return this.loaded?this.B.suggestion:null};
g.h.Nf=function(){return this.l?W7(this.l).Nf:!1};
g.h.hasNext=function(){return this.l?W7(this.l).hasNext:!1};
g.h.getCurrentTime=function(){return this.H};
g.h.bN=function(){var a=W7(this.l),b=this.g.ea();return{allowSeeking:this.g.ed(),clipEnd:b.clipEnd,clipStart:b.clipStart,current:this.getCurrentTime(),displayedStart:-1,duration:a.getDuration(),ingestionTime:a.C?a.A+P7(a):a.A,isPeggedToLive:1>=(a.C?a.o+P7(a):a.o)-this.getCurrentTime(),loaded:a.I,seekableEnd:a.C?a.o+P7(a):a.o,seekableStart:0<a.B?a.B+P7(a):a.B}};
g.h.cN=function(){this.l&&this.l.rE()};
g.h.dN=function(){this.l&&this.l.sE()};
g.h.fP=function(a){1==a&&(this.I=this.l?W7(this.l):null)};
g.h.UR=function(){var a=y8()?new V7(t8(),void 0):null;if(a){var b=this.A;this.loaded&&this.unload();this.l=a;this.I=null;b.key!=this.o.key&&(this.A=b,this.load())}else g.$e(this.l),this.l=null,this.loaded&&(this.unload(),(a=this.I)&&a.videoId==this.g.ea().videoId&&this.g.eA(a.videoId,R7(a)));this.g.R("videodatachange","newdata",this.g.ea(),3)};
g.h.cC=function(){this.F=[this.o].concat(YCa());var a=u8()||this.o;J8(this,a);this.g.sa("onMdxReceiversChange")};
g.h.SR=function(){var a=u8();J8(this,a)};
g.h.RR=function(){this.A=u8()};
g.h.aN=function(a,b){switch(a){case "casting":return this.loaded;case "receivers":return this.F;case "currentReceiver":return b&&("cast-selector-receiver"==b.key?L7():J8(this,b)),this.loaded?this.A:this.o;case "quickCast":return 2==this.F.length&&"cast-selector-receiver"==this.F[1].key?(b&&L7(),!0):!1}};
g.h.eN=function(){$7(this.l,"sendDebugCommand",{debugCommand:"stats4nerds "})};
g.h.Qc=function(){return!1};g.dY.remote=I8;})(_yt_player);
